### ISSUE TITLE
区块开发支持配置 build/index.html 的 title

### ISSUE THREAD

**Issue by woaizimmy** [ice-lab/iceworks#11]
RT

**Comment by imsobear** [comment]
这个我感觉不是特别关键的功能，确定需要吗。

**Comment by woaizimmy** [comment]
> 这个我感觉不是特别关键的功能，确定需要吗。

感觉有的话体验会更好一些。
因为用户在寻找区块的时候，一般会打开多个区域预览，但是每个区块的 title 都是一样的名称，当用户发现其实之前打开的某个区块更适合的时候——
诶？之前是哪个来着？名称是什么？
忘了，然后只能一个一个地去重新打开，每打开一个就要先记住它的名称，最终才能找到适合的那个。

**Comment by imsobear** [comment]
@woaizimmy 理解，你说的这个主要是针对你们开发的自定义区块还是说官方区块。

**Comment by woaizimmy** [comment]
> @woaizimmy 理解，你说的这个主要是针对你们开发的自定义区块还是说官方区块？

自定义的，同一类的区块比较多，官方的同类的区块不多或许一目了然。

**Comment by ClarkXia** [comment]
## 方案

区块的名称默认通过读取 `package.json` 中的 `blockConfig` 进行展示

```json
{
  ...
  "blockConfig": {
    "name": "BasicDetail",
    "title": "BasicDetail",
    "category": "Information"
  },
  ...
}
```

如果有定制 title 需求，可以针对 `blockConfig.name` 进行修改
