### ISSUE TITLE
配置官方推荐vue物料地址，物料获取失败

### ISSUE THREAD

**Issue by a526672351** [ice-lab/iceworks#111]
![image](https://user-images.githubusercontent.com/5345266/85087420-16cd5e00-b210-11ea-9841-009daec82ac5.png)
settings.json 配置如下：

    "iceworks.materialSources": [
        {
            "name": "PC Web",
            "type": "vue",
            "source": "http://ice.alicdn.com/assets/materials/vue-materials.json",
            "description": "飞冰官方推荐 Vue 物料"
        }
    ]

**Comment by a526672351** [comment]
@alvinhui 除了page buider异常显示空白外，手动安装$ npm init ice ice-app @d2-admin/ice-scaffold
进行项目初始化，组件创建获取是失败的，排查出来原因是需要在package.json的dependencies声明依赖react才可以正常显示，奇葩的bug

**Comment by alvinhui** [comment]
已修复

**Comment by a526672351** [comment]
@alvinhui 最新版本把私服配置地址屏蔽了？
