### ISSUE TITLE
业务组件模板增加测试用例的示例

### ISSUE THREAD

**Issue by imsobear** [ice-lab/iceworks#12]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**

**Comment by imsobear** [comment]
模板代码 https://github.com/ice-lab/material-templates/tree/master/packages/template-react-ts/template/component

**Comment by alvinhui** [comment]
https://github.com/ice-lab/iceworks-cli/issues/6
