### ISSUE TITLE
启动应用时报错

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#162]
**您反馈问题的插件是？**

* 插件名：Iceworks Application Viewer
* 插件版本：v0.1.33

**您遇到问题的操作复现步骤？**

![image](https://user-images.githubusercontent.com/4392234/86431304-0bf1ed80-bd27-11ea-9388-608093693370.png)

点击启动，命令面板报错。

**您期待的正确结果？**

期望启动时如果相关命令行工具没有安装则自动帮我进行依赖安装。

**Comment by luhc228** [comment]
Fixed by Release 0.1.7.
