### ISSUE TITLE
当工作区为空时，没有唤起欢迎侧边栏

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#180]
* 插件名：iceworks-team.iceworks-app
* 插件版本：v0.1.34

## 您遇到的问题及复现步骤？

1. 新建 VS Code 窗口
2. 点击 Iceworks 图标，出现如下视图：

    ![image](https://user-images.githubusercontent.com/4392234/86730768-75dd0080-c061-11ea-961e-4bcb7b737b9b.png)

## 您期待的正确结果？

出现欢迎侧边栏和创建应用的引导页：

![image](https://user-images.githubusercontent.com/4392234/86731014-afae0700-c061-11ea-8e03-8b8051aa2565.png)

**Comment by luhc228** [comment]
#198 已发布版本修复
