### ISSUE TITLE
进入创建应用流程，默认选择一个模板

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#181]
### 问题描述

进入创建应用流程，然后直接点击下一步，弹出了「请选择一个模板」：

![image](https://user-images.githubusercontent.com/4392234/86732096-b2f5c280-c062-11ea-87ea-41b44f2f71d7.png)

### 建议的解决方案

进入创建应用流程，默认选中一个模板，方便用户快速启动：

![image](https://user-images.githubusercontent.com/4392234/86732191-ca34b000-c062-11ea-9603-5f3cfd8c75db.png)

### 附加信息

注意在切换了左侧物料源后，需保持之前的选择。

**Comment by luhc228** [comment]
Fixed by Release 0.1.7.
