### ISSUE TITLE
在 JSX 文件点击鼠标右键列表唤起的列表中显示「添加物料」

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#182]
### 问题描述

目前只能通过状态栏右下角或命令面板输入命名的方式唤起添加物料插件，唤起路径较长。

### 建议的解决方案

在 JSX 文件点击鼠标右键唤起的列表中显示「添加物料」：

![image](https://user-images.githubusercontent.com/4392234/86733562-e1c06880-c063-11ea-8cdd-c21830bfe491.png)

### 考虑的备选方案

注册快捷键用于唤起「添加物料面板」。

**Comment by luhc228** [comment]
Fixed by Release 0.1.7.
