### ISSUE TITLE
模板信息优化

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#184]
### 问题描述

模板的名称不太表意：

![image](https://user-images.githubusercontent.com/4392234/86737959-429d7000-c067-11ea-9b18-841716da8884.png)

### 建议的解决方案

- Scaffold Lite => Fusion Design Lite
- Scaffold Simple => Simple

### 附加信息

物料源数据是根据  https://github.com/alibaba-fusion/materials 内的模板包 package.json 生成的

可以提 PR 或 issue 到该仓库。

**Comment by luhc228** [comment]
https://github.com/alibaba-fusion/materials/pull/35
