### ISSUE TITLE
添加依赖的输入框提示文案优化

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#185]
### 问题描述

添加依赖时会弹出文本输入框：

![image](https://user-images.githubusercontent.com/4392234/86743962-d709d180-c06b-11ea-9a21-b56e582ce339.png)

1. 需要是中文
2. 需要说明可以通过空格的方式添加多个依赖（目前用户以为只可以添加一个依赖）

### 建议的解决方案

请输入您需要安装的 npm 包名，通过空格分隔多个包。例如：lodash / lodash@lastest / lodash react / lodash@lastest react@^16.8.0

**Comment by shaojun427** [comment]
![image](https://user-images.githubusercontent.com/16127112/86772523-ca46a700-c086-11ea-8441-d0239588cbd4.png)
![image](https://user-images.githubusercontent.com/16127112/86772501-c1ee6c00-c086-11ea-8fac-27893cc5195f.png)
建议可以这样

**Comment by luhc228** [comment]
![image](https://user-images.githubusercontent.com/44047106/86928421-1a953600-c167-11ea-8969-3fde96db5bb3.png)
