### ISSUE TITLE
命令面板梳理

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#186]
### 问题描述

![image](https://user-images.githubusercontent.com/4392234/86744914-88a90280-c06c-11ea-874a-4a42ed7feb9b.png)

- 目前的命令中，即有中文又有英文
- 命令列表中缺失了部分功能的命令唤起

### 建议的解决方案

- 命令默认使用中文
- 添加以下命令:
    - Iceworks: 添加依赖
    - Iceworks: 添加运行时依赖
    - Iceworks: 添加开发时依赖
    - Iceworks: 重装依赖

**Comment by luhc228** [comment]
Fixed by Release 0.1.7.
