### ISSUE TITLE
物料导入插件功能缺陷

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#200]
* 插件名：iceworks-material-import
* 插件版本：v0.1.1

## 您遇到的问题及复现步骤？

- 物料面板滚动区域有误，滚动时无法切换物料源
- 缺少物料源配置按钮

![image](https://user-images.githubusercontent.com/4392234/86913253-f62e5f00-c150-11ea-97e9-1e0b3d772b91.png)

## 您期待的正确结果？

- 只滚动物料列表，物料源切换和搜索框位置固定
- 添加物料源配置按钮

![image](https://user-images.githubusercontent.com/4392234/86913298-09412f00-c151-11ea-80c0-280aed20c0ad.png)

**Comment by luhc228** [comment]
Fixed by Release 0.1.7.
