### ISSUE TITLE
应用配置帮助插件提示有误

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#205]
* 插件名：iceworks-config-helper
* 插件版本：v0.1.1

## 您遇到的问题及复现步骤？

在 icejs 编辑 build.json 时的代码提示有误：

![image](https://user-images.githubusercontent.com/4392234/87017942-377f4700-c203-11ea-8dae-8adad9ded9e6.png)

## 您期待的正确结果？

在 icejs 和 rax-app 项目的 build.json 有各自域的代码提示。

**Comment by fyangstudio** [comment]
#262
