### ISSUE TITLE
配置了私服地址，可初始化得时候不起效

### ISSUE THREAD

**Issue by a526672351** [ice-lab/iceworks#216]
![image](https://user-images.githubusercontent.com/5345266/87145743-5e5d7c00-c2dc-11ea-9f93-95b25fab1c7b.png)
![image](https://user-images.githubusercontent.com/5345266/87145754-64ebf380-c2dc-11ea-87e8-2adc85b94dad.png)

另外：配置过一次后，第二次打开自定义的数据会丢失

**Comment by luhc228** [comment]
配置完自定义物料源信息以后，有点击右上角的刷新按钮刷新一下物料源信息吗？

**Comment by luhc228** [comment]
需要配置自定义镜像源地址

**Comment by a526672351** [comment]
> 配置完自定义物料源信息以后，有点击右上角的刷新按钮刷新一下物料源信息吗？
> 
> 哪一些自定义信息？

右上角并没有刷新按钮

**Comment by a526672351** [comment]
> 需要配置自定义镜像源地址

就是配置了，不生效
