### ISSUE TITLE
Will `stylus` benchmark be on board?

### ISSUE THREAD

**Issue by coldfannn** [ice-lab/iceworks#221]
### 问题描述

stylus support

**Comment by fyangstudio** [comment]
可更详细的描述下这个问题吗？ 目前是怎样使用 stylus 的，有什么不便的地方

**Comment by coldfannn** [comment]
使用classnames和css modules，目前暂不支持stylus

**Comment by fyangstudio** [comment]
最近几个版本 还没有计划支持。 请问您有兴趣贡献代码吗 ：)
