### ISSUE TITLE
规范化插件说明文档

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#229]
## 目标

提升用户使用体验。

## 手段

根据模板规范所有插件的说明文档：

- 仅更新插件，不更新套件（即不需要更新 `extensions/iceworks/*.md`）。
- 请同时更新插件的 README.md 和 README.en.md
- 确保使用的是最新版本的插件（通过对比[插件市场的插件版本](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks)和本地插件版本）
- VS Code 窗口的截图和录屏：（[参考](https://user-images.githubusercontent.com/4392234/87250444-539b1680-c497-11ea-8643-64098d956ca5.png)）
    - 尺寸：需确保在一篇文档内所有截图使用同一尺寸。
        - 1024*768（VS Code 默认窗口大小） 或
        - 1440*900（13 寸笔记本全屏）
    - 只包含 VS Code 窗口（不包含系统边栏、桌面或其他不相关的内容）
    - VS Code 窗口中的活动栏和侧边栏大小在所有的截图和录屏中需始终保持一致（[参考尺寸](https://user-images.githubusercontent.com/4392234/87248128-4a577d00-c48a-11ea-82b2-0bf8e5047d4f.png)）
- 代码编辑区截图和录屏：（[参考](https://user-images.githubusercontent.com/4392234/87250505-ec319680-c497-11ea-8b31-0fb9f76251fc.png)）
    - 尺寸：764*724
    - 只包含代码编辑区（不包含 VS Code 其他部分）：标签栏、文件树面包屑、代码编辑器、小地图。
- 截图和录屏文件不大于 1 MB

### 模板

```
简体中文 | [English](./README.en.md)

[![插件版本徽标]][插件市场链接]
[![插件下载徽标]][插件市场链接]

[插件市场链接]: https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks
[插件版本徽标]: https://vsmarketplacebadge.apphb.com/version/iceworks-team.iceworks.svg
[插件下载徽标]: https://vsmarketplacebadge.apphb.com/installs-short/iceworks-team.iceworks.svg

# Iceworks XXX插件

一句话介绍插件。

## 功能

### 功能一

#### 唤起（选填）

![唤起录屏说明](唤起录屏说明.gif)

通过怎样的方式唤起该功能。

#### 子功能

子功能介绍。

##### 用法一

用法一介绍。

![操作录屏说明](操作录屏图像.gif)

1. 操作步骤一说明
2. 操作步骤二说明
3. 操作步骤三说明

## 更多

访问 [Iceworks 套件](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks)获取更多功能。

## License

[MIT](https://github.com/ice-lab/iceworks/blob/master/LICENSE)
```

### 简单示例

该示例是页面生成插件。

> 示例中的演示图仅做占位，可能不符合截图或录屏的要求。

```md
简体中文 | [English](./README.en.md)

[![Version](https://vsmarketplacebadge.apphb.com/version/iceworks-team.iceworks-page-builder.svg)](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-page-builder)
[![Installs](https://vsmarketplacebadge.apphb.com/installs-short/iceworks-team.iceworks-page-builder.svg)](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-page-builder)

# Iceworks 页面生成插件

通过可视化操作，以区块拼装的方式生成页面。

## 功能

### 唤起

![唤起生成页面](https://img.alicdn.com/tfs/TB1wFrrek9l0K4jSZFKXXXFjpXa-1024-766.gif)

1. 通过 `⇧⌘P` 快捷键唤起命令面板
2. 在命令面板中输入 `Iceworks: 创建页面` ，点击选中的项目或按下键盘回车键，唤起页面生成插件

### 使用

![使用生成页面](https://img.alicdn.com/tfs/TB1mdpDJKT2gK0jSZFvXXXnFXXa-960-600.gif)

1. 输入页面名称（将用作文件夹名）
2. 从右侧的区块列表中选择页面需要使用的区块，点击添加到左侧页面预览区
3. 在左侧页面预览区可通过拖拽排序区块的顺序，或点击右上角的删除图标移除区块
3. 点击“生成页面”按钮，生成页面代码，页面代码将生成到 `src/pages/${页面名称}`

## 更多

访问 [Iceworks 套件](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks)获取更多功能。

## License

[MIT](https://github.com/ice-lab/iceworks/blob/master/LICENSE)
```

### 复杂示例

该示例是样式开发辅助插件。

> 示例中的演示图仅做占位，可能不符合截图或录屏的要求。

```md
简体中文 | [English](./README.en.md)

[![Version](https://vsmarketplacebadge.apphb.com/version/iceworks-team.iceworks-style-helper.svg)](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper)
[![Installs](https://vsmarketplacebadge.apphb.com/installs-short/iceworks-team.iceworks-style-helper.svg)](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks-style-helper)

# Iceworks 样式开发辅助插件

在 [JSX](https://zh-hans.reactjs.org/docs/introducing-jsx.html) 中更快速地编写内联样式，对 React 和 [Rax](https://rax.js.org/) 应用友好。

## 用法

### JSX 文件

#### style 属性

在 JSX 文件中编辑组件的 `style` 属性时给予自动补全提醒。

##### 行内样式

根据 w3c 标准给予样式字段和值的自动补全提醒：

![使用示例](https://img.alicdn.com/tfs/TB1oyRBF1H2gK0jSZFEXXcqMpXa-1000-586.gif)

##### 变量赋值

使用 CSS Module 时，根据样式声明进行样式字段的自动补全：

![使用示例](https://img.alicdn.com/tfs/TB1UDGht.Y1gK0jSZFMXXaWcVXa-1468-906.gif)

#### className 属性

在 JSX 文件中编辑组件的 `className` 属性时给予自动补全提醒，值预览及定义跳转。

##### 自动补全提醒

在编辑组件的 `className` 时，根据文件 `import` 的样式文件内的类选择器进行自动补全提醒：

![使用示例](https://img.alicdn.com/tfs/TB1JqP0Nfb2gK0jSZK9XXaEgFXa-900-561.gif)

##### 值预览及定义跳转

![使用示例](https://img.alicdn.com/tfs/TB1JqP0Nfb2gK0jSZK9XXaEgFXa-900-561.gif)

- 鼠标停留在 `className` 值上，出现悬浮部件显示该值对应的样式声明
- 点击对应的 `className` 值，跳转到该值的定义处

### 样式文件

在 CSS、LESS、SASS 文件中输入类选择器时，根据引用值进行自动补全提醒：

![使用示例](https://img.alicdn.com/tfs/TB1l_zMFhD1gK0jSZFKXXcJrVXa-500-355.gif)

- 在 JSX 内声明某个组件 `className` 属性的值为 `test`
- 在 JSX 内引用样式文件：`import './index.csss'`
- 新建该 `index.css` 文件
- 在 `index.css` 内输入 `.t` ，出现 `.test` 的自动补全提醒

### SASS 文件

#### 变量自动补全提醒

在 SASS 文件内输入变量时，根据引用文件进行代码自动补全：

![使用示例](https://img.alicdn.com/tfs/TB1RA_ZMeL2gK0jSZPhXXahvXXa-900-535.gif)

#### 变量预览值

鼠标停留在变量上，出现悬浮部件显示该变量对应的值：

![使用示例](https://img.alicdn.com/tfs/TB1RA_ZMeL2gK0jSZPhXXahvXXa-900-535.gif)

#### 属性值使用变量替换的建议

输入属性值时，如发现可使用变量进行替换，则出现变量替换提醒列表：

![使用示例](https://img.alicdn.com/tfs/TB1RA_ZMeL2gK0jSZPhXXahvXXa-900-535.gif)

#### 变量的定义跳转

通过 cmd + 点击（ Windows: ctrl + 点击 ）进行变量的定义代码跳转：

![使用示例](https://img.alicdn.com/tfs/TB1RA_ZMeL2gK0jSZPhXXahvXXa-900-535.gif)

## 更多

访问 [Iceworks 套件](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks)获取更多功能。

## License

[MIT](https://github.com/ice-lab/iceworks/blob/master/LICENSE)
```

## PR 说明

- 请基于 `release/0.2.0` 拉取开发分支
- 请将 PR 指向 `release/0.2.0`

## PR 要求

- 时间：周三提交 PR ，周四早上合并入 Release 分支
- 质量：两轮 Review 后可 Merge 入 `release/0.2.0`

## 提示

- MacOS 的截图和录屏可使用系统自带的工具，通过 `⇧⌘5`唤起。录屏后，通过 PicGIF Lite 等工具转换成 Gif
- 图片粘贴到 issue 即可上传到 Github 自带的 CDN

**Comment by sspku-yqLiu** [comment]
### iceworks-app

- 图形化唤起页面和组件构造功能说明
    ![图形化唤起页面和组件构造功能说明](https://user-images.githubusercontent.com/56879942/87393953-949f4200-c5e1-11ea-896a-fd2d592050e0.gif)
-  页面和组件信息跳转说明
    ![页面和组件信息跳转说明](https://user-images.githubusercontent.com/56879942/87393958-9963f600-c5e1-11ea-9c96-94fc10492577.gif)
- 安装依赖说明
    ![安装依赖说明](https://user-images.githubusercontent.com/56879942/87393970-9bc65000-c5e1-11ea-9724-3bd47c4b21ed.gif)
- 应用依赖更新说明
    ![应用依赖更新说明](https://user-images.githubusercontent.com/56879942/87393973-9cf77d00-c5e1-11ea-8baa-96c8c41229cf.gif)
- 执行和中断脚本说明
    ![执行和中断脚本说明](https://user-images.githubusercontent.com/56879942/87393980-9f59d700-c5e1-11ea-9e07-0244926f54cc.gif)

**Comment by sspku-yqLiu** [comment]
### 组建创建插件

- 组建创建插件说明
    ![组建创建插件说明](https://user-images.githubusercontent.com/56879942/87396941-2c069400-c5e6-11ea-8df8-f0ff5879da3b.gif)

**Comment by sspku-yqLiu** [comment]
### 应用配置辅助开发插件

- 悬停提示
    ![应用配置辅助开发插件-悬停提示说明](https://user-images.githubusercontent.com/56879942/87398212-290ca300-c5e8-11ea-9596-c15c380c0d7c.gif)
- 自动补全
    ![应用配置辅助开发插件-自动补全说明](https://user-images.githubusercontent.com/56879942/87398228-2e69ed80-c5e8-11ea-8b2e-611924fa76bb.gif)
- 代码片段
    ![应用配置辅助开发插件-代码片段说明](https://user-images.githubusercontent.com/56879942/87398223-2d38c080-c5e8-11ea-8eef-2f208f498210.gif)

**Comment by sspku-yqLiu** [comment]
### 物料使用辅助插件

- 物料使用辅助插件-补全说明
    ![物料使用辅助插件-补全说明](https://user-images.githubusercontent.com/56879942/87399599-2dd25680-c5ea-11ea-9402-5e36ba7b8f98.gif)

**Comment by sspku-yqLiu** [comment]
### 物料添加插件

- 物料添加插件说明
    ![物料添加插件说明](https://user-images.githubusercontent.com/56879942/87401390-a63a1700-c5ec-11ea-91a6-f7d81ac5fd77.gif)

**Comment by sspku-yqLiu** [comment]
### 页面生成插件

- 页面生成插件-唤起
    ![CreatePage-WakeUp](https://user-images.githubusercontent.com/56879942/87402315-f49be580-c5ed-11ea-87a8-4143a461124f.gif)
- 页面生成插件-使用
    ![CreatePage-Usage](https://user-images.githubusercontent.com/56879942/87402326-f82f6c80-c5ed-11ea-8ffe-34263e8dd0be.gif)

**Comment by sspku-yqLiu** [comment]
### 创建应用插件

- 创建应用插件-默认唤醒
![创建应用插件-默认唤醒](https://user-images.githubusercontent.com/56879942/87407459-c4a41080-c5f4-11ea-882e-d198afc35413.png)
- 创建应用插件-唤醒
    ![创建应用插件-唤醒](https://user-images.githubusercontent.com/56879942/87407446-c1108980-c5f4-11ea-9d27-584cebad1efe.gif)
- 创建应用插件-设定包管理工具及镜像源
    ![创建应用插件-设定包管理工具及镜像源](https://user-images.githubusercontent.com/56879942/87407462-c53ca700-c5f4-11ea-9c0b-8232ed9b3529.gif)
- 创建应用插件-创建应用说明
    ![创建应用插件-创建应用说明](https://user-images.githubusercontent.com/56879942/87407423-bb1aa880-c5f4-11ea-8927-8e1d75b73164.gif)

**Comment by sspku-yqLiu** [comment]
### 样式开发辅助插件

- 样式开发辅助插件-行内样式补全
    ![样式开发辅助插件-行内样式补全](https://user-images.githubusercontent.com/56879942/87412958-3895e700-c5fc-11ea-88e2-3e3e78a07f9e.gif)  
- 样式开发辅助插件-CSSModule变量赋值
    ![样式开发辅助插件-CSSModule变量赋值](https://user-images.githubusercontent.com/56879942/87412953-36cc2380-c5fc-11ea-9315-f153b1415dc8.gif)
- 样式开发辅助插件-className补全
    ![样式开发辅助插件-className补全](https://user-images.githubusercontent.com/56879942/87412926-2caa2500-c5fc-11ea-9acc-78974ddb1932.gif)  
- 样式开发辅助插件-className值预览及跳转帮助
    ![样式开发辅助插件-className值预览及跳转帮助](https://user-images.githubusercontent.com/56879942/87412950-35026000-c5fc-11ea-83ee-33de13681911.gif)
- SCSS、LESS、SASS类选择器的自动补全
    ![SCSS、LESS、SASS类选择器的自动补全](https://user-images.githubusercontent.com/56879942/87414084-c58d7000-c5fd-11ea-8f9d-716f8053fd9a.gif)
- 样式开发辅助插件-SCSS引用文件的自动补全
    ![样式开发辅助插件-SCSS引用文件的自动补全](https://user-images.githubusercontent.com/56879942/87409692-e3f06d00-c5f7-11ea-970c-76b0cf829851.gif)   
- 样式开发辅助插件-SCSS变量值预览  
    ![样式开发辅助插件-SCSS变量值预览 ](https://user-images.githubusercontent.com/56879942/87412974-3e8bc800-c5fc-11ea-9a6c-ea62eecbfbff.gif)
- 样式开发辅助插件-SCSS变量的跳转
    ![样式开发辅助插件-SCSS变量的跳转](https://user-images.githubusercontent.com/56879942/87412960-3a5faa80-c5fc-11ea-87f9-cda6cdc2f530.gif)
- 样式开发辅助插件-SASS变量重定义
    ![样式开发辅助插件-SASS变量重定义](https://user-images.githubusercontent.com/56879942/87412975-3fbcf500-c5fc-11ea-82ed-89bfa1349811.gif)

**Comment by sspku-yqLiu** [comment]
- 补发一张有问题的图片
![样式开发辅助插件-SCSS变量的跳转](https://user-images.githubusercontent.com/56879942/87416514-63366e80-c601-11ea-8f3e-05fe51a8f26b.gif)

**Comment by sspku-yqLiu** [comment]
至此 ，大部分动图已经上传完毕
有一些涉及到中英文版本不同的需要进行二次录屏，再之后会上传
请检验一下是否存在不合规的照片
------------------------我是分割线------------------------

**Comment by sspku-yqLiu** [comment]
图片补发：
![StyleHelper-SCSS-Completion](https://user-images.githubusercontent.com/56879942/87523081-026a6d00-c6b9-11ea-8e8a-5d62688c020d.gif)

**Comment by sspku-yqLiu** [comment]
### 根据反馈更新的GIF

#### app 插件

- 启动
    ![2-app-启动插件](https://user-images.githubusercontent.com/56879942/87531784-cb01bd80-c6c4-11ea-816b-fff4336016fd.gif)

- 命令办介绍
    ![2-app-命令版](https://user-images.githubusercontent.com/56879942/87531795-d05f0800-c6c4-11ea-84d3-8e5fcfc32348.gif)

- 设置 npm 
    ![2-app-设置](https://user-images.githubusercontent.com/56879942/87531798-d1903500-c6c4-11ea-9c6d-e19d6241c91a.gif)

#### ComponentBuilder 插件

- 生成组件
    ![2-ComponentBuilder-生成组件](https://user-images.githubusercontent.com/56879942/87531857-e5d43200-c6c4-11ea-81ce-a47b2a35174f.gif)

#### PageBuilder 插件

- 创建页面
    ![2-PageBuilder-创建页面](https://user-images.githubusercontent.com/56879942/87531900-f5ec1180-c6c4-11ea-8753-ad269d5768d5.gif)

#### StyleHelper 插件
- 自动补全
    ![2-styleHelper-SCSS自动补全](https://user-images.githubusercontent.com/56879942/87531943-04d2c400-c6c5-11ea-9f74-be6721353e46.gif)

**Comment by sspku-yqLiu** [comment]
### Compotent Builder

-  wakeup
    ![2 1-ComponentBuilder-唤醒](https://user-images.githubusercontent.com/56879942/87535699-77926e00-c6ca-11ea-9e21-65fad2e95e0f.gif)
- Usage
    ![2 1-ComponentBuilder-生成组件](https://user-images.githubusercontent.com/56879942/87535673-6f3a3300-c6ca-11ea-852e-f3a2bb3eb7bc.gif)

**Comment by sspku-yqLiu** [comment]
### material Import 

- 唤醒
    ![2 2-MaterialImport-唤醒](https://user-images.githubusercontent.com/56879942/87538941-a19a5f00-c6cf-11ea-92f2-b8ed100792fc.gif)
- 使用
    ![2 2-MaterialImport-使用](https://user-images.githubusercontent.com/56879942/87538909-95ae9d00-c6cf-11ea-8c02-881e3fcc8f0a.gif)

**Comment by sspku-yqLiu** [comment]
### Project-Creater
- 使用
    ![2 3-ProjectBuider-use](https://user-images.githubusercontent.com/56879942/87541340-acef8980-c6d3-11ea-87c6-68fc4b0b094c.gif)
- 唤醒
    ![2 3-ProjectCreater-唤醒](https://user-images.githubusercontent.com/56879942/87541327-aa8d2f80-c6d3-11ea-8540-9a1ad888e723.gif)
- 设置
    ![2 3-ProjectCreater-设置](https://user-images.githubusercontent.com/56879942/87541316-a52fe500-c6d3-11ea-8726-104930de7313.gif)

**Comment by sspku-yqLiu** [comment]
### 唤起命令版
![2 4-app-callcommand](https://user-images.githubusercontent.com/56879942/87544740-8d5b5f80-c6d9-11ea-85ff-bc31501911e1.gif)

**Comment by sspku-yqLiu** [comment]
## Review 2
### APP
- 激活
    ![3-app-激活](https://user-images.githubusercontent.com/56879942/87553484-8e928980-c6e5-11ea-8183-a6ba7f4eae95.gif)

**Comment by sspku-yqLiu** [comment]
### materialHelper
 - 页面引用
    ![3-materialImporter-页面引用](https://user-images.githubusercontent.com/56879942/87619860-ba4a5980-c74f-11ea-84c1-9ef69ef17b18.gif)
- 组件引用
    ![3-materialHelper-组件](https://user-images.githubusercontent.com/56879942/87619875-c2a29480-c74f-11ea-945e-788a32e65881.gif)

### 创建应用插件

- 激活
    ![3-projectCreated-激活](https://user-images.githubusercontent.com/56879942/87619873-c209fe00-c74f-11ea-9da9-238a041a32d3.gif)

- 设置
    ![3-projectCreated-设置](https://user-images.githubusercontent.com/56879942/87619871-c0d8d100-c74f-11ea-803e-a023bc77b0f4.gif)

**Comment by sspku-yqLiu** [comment]
### Project-Creater

- 激活
    ![3 1-createProject-激活](https://user-images.githubusercontent.com/56879942/87621232-e61b0e80-c752-11ea-852c-77bb164d2dab.gif)
- 设置
    ![3 1-createProject-设置](https://user-images.githubusercontent.com/56879942/87621238-eadfc280-c752-11ea-8efc-483835153321.gif)

**Comment by sspku-yqLiu** [comment]
- 创建项目更新（不带 Iceworks 侧边栏）
![3 1-createProject-创建项目](https://user-images.githubusercontent.com/56879942/87621825-41013580-c754-11ea-8da8-e49e71397d08.gif)

**Comment by sspku-yqLiu** [comment]
### 国际版图片

![materialImportPage](https://user-images.githubusercontent.com/56879942/88175399-657b7700-cc58-11ea-82d0-a0a29e23195e.gif)
![createAppWakeUP](https://user-images.githubusercontent.com/56879942/88175416-6b715800-cc58-11ea-9ddf-1af448b71054.gif)
![materialImportComponent](https://user-images.githubusercontent.com/56879942/88175419-6c09ee80-cc58-11ea-9de0-8e397a48049b.gif)
![createPageUsage](https://user-images.githubusercontent.com/56879942/88175424-6d3b1b80-cc58-11ea-961d-8bac1cb3f812.gif)
![createPageWakpUP](https://user-images.githubusercontent.com/56879942/88175431-6e6c4880-cc58-11ea-9bed-81366cf8e445.gif)
![createAppUsage](https://user-images.githubusercontent.com/56879942/88175435-6f9d7580-cc58-11ea-8a88-f74a5ab4f674.gif)

**Comment by sspku-yqLiu** [comment]
### 国际化录屏补充

#### ComponentBuilder

![componentBuilderWakeUp](https://user-images.githubusercontent.com/56879942/88181877-0b7faf00-cc62-11ea-9b90-3808f43d0499.gif)

![componentBuilderUsage](https://user-images.githubusercontent.com/56879942/88181864-06bafb00-cc62-11ea-92a2-b1d05f9cb161.gif)

#### createApplication

![createApplicationWakeUp](https://user-images.githubusercontent.com/56879942/88181928-1e927f00-cc62-11ea-94fb-06d12dab77d1.gif)

**Comment by sspku-yqLiu** [comment]
### Component Builder 修正

![2-ComponentBuilderUsage](https://user-images.githubusercontent.com/56879942/88187064-a4b1c400-cc68-11ea-9d47-fac137d1f8c7.gif)
![2-ComponentBuilderWakeUp](https://user-images.githubusercontent.com/56879942/88187088-a9767800-cc68-11ea-970d-df0bb4c9e94a.gif)

**Comment by sspku-yqLiu** [comment]
### 更新错误画面

![2-ComponentBuilderUsage](https://user-images.githubusercontent.com/56879942/88188623-af6d5880-cc6a-11ea-8b33-3304926f5ce7.gif)
![2-ComponentBuilderWakeUp](https://user-images.githubusercontent.com/56879942/88188643-b4320c80-cc6a-11ea-9cbd-251fd6d8acf1.gif)

**Comment by sspku-yqLiu** [comment]
### material-helper 及 pageBuilder 修改

![2-MaterialHelperWakeUp](https://user-images.githubusercontent.com/56879942/88197902-b2ba1180-cc75-11ea-8e33-0ce4e7faa368.gif)
![2-MaterialHelperPage](https://user-images.githubusercontent.com/56879942/88197928-b8aff280-cc75-11ea-816d-1c609bc90878.gif)
![2-PageBuilderUsage](https://user-images.githubusercontent.com/56879942/88197942-bb124c80-cc75-11ea-8caa-68fe2dc4cbc3.gif)
![2-MaterialHelperComponent](https://user-images.githubusercontent.com/56879942/88197950-bd74a680-cc75-11ea-8650-dec13706366c.gif)
![2-PageBuilderWakUp](https://user-images.githubusercontent.com/56879942/88197953-bf3e6a00-cc75-11ea-81c2-b75a55d649bd.gif)

**Comment by sspku-yqLiu** [comment]
### ConfigHelperDoc
![use-UsePanel](https://user-images.githubusercontent.com/56879942/89489431-12b7c880-d7dd-11ea-9802-8f3fa51304f0.gif)
![init-侧边栏](https://user-images.githubusercontent.com/56879942/89489442-18ada980-d7dd-11ea-8db3-1751e5db2eca.gif)
![init-InFile](https://user-images.githubusercontent.com/56879942/89489443-19464000-d7dd-11ea-9eeb-2958027525c4.gif)

**Comment by sspku-yqLiu** [comment]
![usage-en](https://user-images.githubusercontent.com/56879942/89491159-30872c80-d7e1-11ea-9463-501248e1b08c.gif)
![init-context-en](https://user-images.githubusercontent.com/56879942/89491449-e94d6b80-d7e1-11ea-8780-051ff9845023.gif)
![init-sidbar-en](https://user-images.githubusercontent.com/56879942/89491695-68db3a80-d7e2-11ea-8bfe-af1b545eb2ad.gif)

**Comment by sspku-yqLiu** [comment]
config Helper 打开源文件

![打开源文件](https://user-images.githubusercontent.com/56879942/90103045-7493a780-dd74-11ea-836c-13ad2a3ad3d5.gif)

**Comment by sspku-yqLiu** [comment]
Material Helper / Component Doc
![startInfile](https://user-images.githubusercontent.com/56879942/90105027-cc7fdd80-dd77-11ea-89f8-48b2a8d566eb.gif)
![使用](https://user-images.githubusercontent.com/56879942/90105039-d1449180-dd77-11ea-9497-1e29a96b16e9.gif)
![startInterminal](https://user-images.githubusercontent.com/56879942/90105043-d275be80-dd77-11ea-9723-0ce16206c134.gif)
![文件中启动](https://user-images.githubusercontent.com/56879942/90105045-d3a6eb80-dd77-11ea-9d4e-e0f4433e36c1.gif)
![设置](https://user-images.githubusercontent.com/56879942/90105048-d4d81880-dd77-11ea-8fcf-76da90af3a23.gif)
![usage](https://user-images.githubusercontent.com/56879942/90105051-d570af00-dd77-11ea-86b6-b460fa6cf430.gif)
![启动](https://user-images.githubusercontent.com/56879942/90105060-d73a7280-dd77-11ea-8cb6-dbda547adcf2.gif)
![setting](https://user-images.githubusercontent.com/56879942/90105064-d86b9f80-dd77-11ea-999e-d93974b9e6c5.gif)

**Comment by sspku-yqLiu** [comment]
![悬浮提示](https://user-images.githubusercontent.com/56879942/90107037-d6571000-dd7a-11ea-8048-60eb2e0689db.gif)
![Use_Hover](https://user-images.githubusercontent.com/56879942/90107055-dbb45a80-dd7a-11ea-98eb-6fa6ecf3acc8.gif)

**Comment by sspku-yqLiu** [comment]
### 文章图片
![image-20200813194129485](https://user-images.githubusercontent.com/56879942/90135711-aa04b900-dda5-11ea-9f0b-a00b00414fd0.png)
![image-20200813194218580](https://user-images.githubusercontent.com/56879942/90135722-aec96d00-dda5-11ea-827c-3d9b709e5145.png)
![image-20200813195544661](https://user-images.githubusercontent.com/56879942/90135727-affa9a00-dda5-11ea-9173-ae4f089242f6.png)
![image-20200813195902352](https://user-images.githubusercontent.com/56879942/90135728-b0933080-dda5-11ea-8495-d2d0c62129e4.png)
![image-20200813200914082](https://user-images.githubusercontent.com/56879942/90135731-b12bc700-dda5-11ea-9be9-f22ea8a7e9f4.png)
![image-20200813201549437](https://user-images.githubusercontent.com/56879942/90135734-b1c45d80-dda5-11ea-9ffc-74fa49320c31.png)

**Comment by sspku-yqLiu** [comment]
page intro 
![image](https://user-images.githubusercontent.com/56879942/90782290-6f64c880-e331-11ea-9f9a-46099e11a7b9.png)

**Comment by sspku-yqLiu** [comment]
ui-builder-page-material
![启动-createpage-zhcn](https://user-images.githubusercontent.com/56879942/91519104-442b3c00-e924-11ea-93a3-e52bbc83f05d.gif)
![wakeup-createpage-enus](https://user-images.githubusercontent.com/56879942/91519113-4a211d00-e924-11ea-8fbe-36170dedc765.gif)
![use-createpage-enus](https://user-images.githubusercontent.com/56879942/91519118-4c837700-e924-11ea-80f4-1919380c7d9f.gif)
![使用-createpage-zhcn](https://user-images.githubusercontent.com/56879942/91519125-52795800-e924-11ea-904f-9cc0caf6af5e.gif)

**Comment by sspku-yqLiu** [comment]
V2
![usage-createpage-enusV2](https://user-images.githubusercontent.com/56879942/91536884-03451e80-e948-11ea-98e6-6bf89b62e932.gif)
![使用-createpage-zhcnV2](https://user-images.githubusercontent.com/56879942/91536902-08a26900-e948-11ea-9c80-41fe4387b48f.gif)

**Comment by sspku-yqLiu** [comment]
![image](https://user-images.githubusercontent.com/56879942/91725804-d0ae5680-ebd1-11ea-9716-d7273e816280.png)

**Comment by sspku-yqLiu** [comment]
![end-en-us](https://user-images.githubusercontent.com/56879942/95042184-afc6ad00-070b-11eb-98be-21c65f292c40.gif)
![end-zh-CN](https://user-images.githubusercontent.com/56879942/95042192-b7865180-070b-11eb-83de-50ad3af29b4a.gif)
![start-en-us](https://user-images.githubusercontent.com/56879942/95042198-bb19d880-070b-11eb-95fd-bfc778c55a5f.gif)
![usage-en-us](https://user-images.githubusercontent.com/56879942/95042207-bead5f80-070b-11eb-8828-28d3adc2b137.gif)
![start-zh-CN](https://user-images.githubusercontent.com/56879942/95042213-c10fb980-070b-11eb-8e4c-0193e026b8ee.gif)
![usage-zh-CN](https://user-images.githubusercontent.com/56879942/95042215-c2d97d00-070b-11eb-8698-a4ae04136dbf.gif)
