### ISSUE TITLE
config-helper补全与悬浮提示在一些条件下无法触发，且不能对所有插件进行提示。

### ISSUE THREAD

**Issue by sspku-yqLiu** [ice-lab/iceworks#240]
* 插件名：iceworks-config-helper
* 插件版本：0.1.1

## 您的本地环境信息？

* 操作系统及其版本：mac 10.15.4
* Node 版本：14.5.0
* npm 版本：6.14.5

## 您遇到的问题及复现步骤？
- 无法识别最新插件(前两个)

![image](https://user-images.githubusercontent.com/56879942/87310267-5279f000-c550-11ea-9ed8-0f1e0b9e3939.png)

- 子配置项的错误导致父配置项无法进行提示

子配置项为targets(正确)时：
![image](https://user-images.githubusercontent.com/56879942/87310472-966cf500-c550-11ea-9bf2-5461fe5d4842.png)

子配置项为target(错误)时：
![image](https://user-images.githubusercontent.com/56879942/87310520-a5ec3e00-c550-11ea-8dd9-f2d0ea6a46d1.png)

- 自动补全提示仅在“”情况下触发，在输入内容后无法触发：

内容为”“时

![image](https://user-images.githubusercontent.com/56879942/87310667-db912700-c550-11ea-9787-df4886bc4e5a.png)

当引号内含有字母时

![image](https://user-images.githubusercontent.com/56879942/87310712-e946ac80-c550-11ea-94df-b7faf5e235d7.png)

## 您期待的正确结果？

- 能够识别合法插件
- 子项错误时父标签仍能正确显示
- 在输入在引号内部有文字的时候也能提供合法的自动不全

**Comment by fyangstudio** [comment]
#262
