### ISSUE TITLE
在添加新页面的时候自动添加路由

### ISSUE THREAD

**Issue by youluna** [ice-lab/iceworks#243]
### 问题描述

目前通过iceworks插件，给现有项目添加页面，只是添加了代码块，希望也能加上路由，这样添加代码之后直接`npm run start` 就可以查看刚添加的页面
### 建议的解决方案

用户的路由形式可能是多种多样的（hash / browser），建议把几种比较通用的路由形式添加进来，先覆盖60%的用户
![image](https://user-images.githubusercontent.com/10049465/87393729-2fe3e780-c5e1-11ea-8c33-83c443bd9061.png)

**Comment by alvinhui** [comment]
路由形式应该是跟着应用走的，除非是应用没有设置路由。

路由的设置形式，可以参考 iceworks 4.0

**Comment by alvinhui** [comment]
我们将在 0.4.0 版本中发布
