### ISSUE TITLE
ICE 站点文档优化

### ISSUE THREAD

**Issue by imsobear** [ice-lab/iceworks#263]
### 问题描述

文档整体优化，目前内容和体验都不太友好

https://ice.work/

**Comment by alvinhui** [comment]
## [WIP] 文档目录

- 从老版本升级
    - 从 2.0 升级
    - 从 3.0 升级
    - 从 4.0 升级

**Comment by alvinhui** [comment]
## 文档目录

- 概述：常见问题
- 快速开始
- 用户指南
    - 创建应用
    - 应用信息概览
    - 应用的预览、调试、构建和发布
    - 创建页面和组件
    - 应用配置
    - 依赖包管理
    - 编码辅助：代码补全、信息提示、组件文档、代码定位
    - 自定义物料
- 附加说明
    - 功能配置和插件管理
    - 从老版本升级：从 2.0 升级、从 3.0 升级、从 4.0 升级
- VS Code 指南
    - 安装
    - 用户界面
    - 资源管理器
    - 代码编辑
    - 源代码管理(Git)
    - 集成终端(Terminal)
    - 设置

**Comment by alvinhui** [comment]
https://github.com/alibaba/ice/pull/3456
