### ISSUE TITLE
插件文档格式规范补充

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#286]
目前插件的文档已统一格式 #229 ，为保障后续的文档质量：

- [x] 接入 MarkdownLint 到 CI 的流程 @sspku-yqLiu 
- [x] 补充插件文档的模板、截图和录屏的尺寸和文件大小规范 @alvinhui

**Comment by sspku-yqLiu** [comment]
### 思路

- 在 package.json 中添加脚本  
    "docs:check":"ts-node ./scripts/docs-check.ts",
- 编写脚本并检测所有 extension 里面的文件。

### 疑问

- 我在网上搜集到的 ci 是使用不同工具的 例如 git-lab travis-ci 等， 我们是用的什么方式实现的 ci 呢？
- 添加脚本的方式是正确的吗，这样会使得脚本检测进入 ci 流程吗？

**Comment by sspku-yqLiu** [comment]
#328

**Comment by alvinhui** [comment]
> ### 思路
> * 在 package.json 中添加脚本
>   "docs:check":"ts-node ./scripts/docs-check.ts",
> * 编写脚本并检测所有 extension 里面的文件。
> 
> ### 疑问
> * 我在网上搜集到的 ci 是使用不同工具的 例如 git-lab travis-ci 等， 我们是用的什么方式实现的 ci 呢？
> * 添加脚本的方式是正确的吗，这样会使得脚本检测进入 ci 流程吗？

https://github.com/ice-lab/iceworks/pull/338
