### ISSUE TITLE
链接脱敏

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#317]
## 背景

目前仓库代码中存在一些 `alibaba-inc.com`的链接，需要脱敏处理。

## 需求

使用编码的方式对链接线下对 URL 进行编码，然后代码中使用编码后字符。示例：

1. 线下编码
    ```js
    import encode from 'encode';
    console.log(encode('https://x.alibaba-inc.com/api/foo'));
    ```
2. 代码中使用编码后字符
    ```diff
    - export const fooUrl = 'https://x.alibaba-inc.com/api/foo';
    + import decode from 'decode';
    + export const fooUrl = decode('encodedString');
    ```

**更新所有 extensions 和 packages 内的含有 `alibaba-inc.com` 的字符串。**

## PR 说明

- 请基于 release/0.3.0 拉取开发分支
- 请将 PR 指向 release/0.3.0

## PR 要求

- 时间：7 月 23 日提交 PR ，7 月 24 日合并入 Release 分支
- 质量：两轮 Review 后可 Merge 入 Release 分支

## 注意

- 编解码可以用社区的工具包
- 所有需编码的字符串应提取为常量并确保只在初始化时进行解码（而不是在函数调用内解码），提高运行时性能
- 以下链接不需要编码
    - https://registry.npm.alibaba-inc.com
    - https://unpkg.alibaba-inc.com
    - https://fusion.alibaba-inc.com

**Comment by imsobear** [comment]
感觉没必要通过 ci 注入，代码里使用编码后的字符就可以了

**Comment by alvinhui** [comment]
> 感觉没必要通过 ci 注入，代码里使用编码后的字符就可以了

ok，我感觉也必要性不大，直接使用对称编码

**Comment by imsobear** [comment]
alibaba-inc 都脱敏下

**Comment by sspku-yqLiu** [comment]
#335
