### ISSUE TITLE
iceworks-project-creator 插件部分英文翻译有误

### ISSUE THREAD

**Issue by luhc228** [ice-lab/iceworks#321]
* 插件名：iceworks-project-creator
* 插件版本：0.2.3

## 您遇到的问题及复现步骤？

![image](https://user-images.githubusercontent.com/44047106/88156164-9e592300-cc3b-11ea-87f8-69caf40a5f8c.png)

1. 副标题可以用一些简单点的单词
2. Next Step --> NEXT

![image](https://user-images.githubusercontent.com/44047106/88156219-b5981080-cc3b-11ea-98d9-a946e173d946.png)

3. Choose a template --> FINISH 
4. 上一步 --> PREVIOUS

## 您期待的正确结果？

可以参考 material-ui 的模板

**Comment by sspku-yqLiu** [comment]
#322

**Comment by sspku-yqLiu** [comment]
修复完成的 demo
![demo (2)](https://user-images.githubusercontent.com/56879942/88166458-dcf5da00-cc49-11ea-98a4-0798f4ac58c4.gif)
