### ISSUE TITLE
应用配置帮助插件功能增强

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#337]
## 背景

在 [icejs](https://ice.work/) 和 [rax-app](https://rax.js.org/) 中存在框架级配置，这些配置对于开发者有一定的学习和使用成本。可通过代码编辑辅助、可视化辅助等方式降低该成本。

例如， tsconfig.json 的编辑在 VS Code 中就有良好的自动补全和悬停信息：

![image](https://user-images.githubusercontent.com/4392234/88353039-9fe73000-cd8e-11ea-83e5-644a0d08d41f.png)

### JSON 的编辑辅助

为以下文件添加自动补全和悬停信息，功能可参考 tsconfig.json 效果。

- icejs:
    - /build.json（[参考说明](https://ice.work/docs/guide/basic/build)）
- rax-app:
    - /build.json （[参考说明](https://rax.js.org/docs/guide/about-rax-scripts)）
    - /src/app.json（[参考说明](https://rax.js.org/docs/guide/app-config)）

> 关于配置内容，icejs 咨询 @chenbin92 ，rax-app 咨询 @fyangstudio 

### JSON 的可视化设置

通过表单交互设置 JSON 配置，其效果可参考 VS Code Settings：

![image](https://user-images.githubusercontent.com/4392234/88353333-a5914580-cd8f-11ea-900c-8105a9270ac2.png)

### 激活方式

0. 在资源管理器面板对目标文件右键，在右键列表里添加「可视化配置」选项，点击该选项唤起可视化配置窗口；
0. 在目标文件在激活窗口时，通过快捷键唤起可视化配置窗口；
0. 参考 VS Code 中对 Markdown 文件预览的处理：
    > 在 Markdown 文件是激活状态时，VS Code 将在编辑标签栏右上角出现「预览」的操作图标，点击后右侧打开 Markdown 预览窗口。

    ![image](https://user-images.githubusercontent.com/4392234/88352752-78dc2e80-cd8d-11ea-9f33-17bef2a0d7da.png)

## PR 说明

- 请基于 release/0.3.0 拉取开发分支
- 请将 PR 指向 release/0.4.0

## PR 要求

- 时间：下周四前提交 PR ，下周五早上合并入 Release 分支
- 质量：两轮 Review 后可 Merge 入 Release 分支

## 参考

相关功能需实现在 iceworks-config-helper 插件内。实现方案参考：

JSON 的编辑辅助： 

- [VS Code - jsonValidation](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation)

JSON 的可视化设置：

- [JSON Schema Form](https://github.com/rjsf-team/react-jsonschema-form)
- [VS Code - Settings](https://code.visualstudio.com/docs/getstarted/settings)

## 附加题

除 JSON 文件外，icejs 和 rax-app 内有一些具备一定规律和格式的 JS 类配置文件，如：

- /src/app.ts [应用配置](https://ice.work/docs/guide/basic/app)
- /src/router.ts [路由配置](https://ice.work/docs/guide/basic/router)
- ...

如何实现动态配置的编辑辅助和可视化辅助？

**Comment by chenbin92** [comment]
预计在 8 月下旬 icejs&raxjs（rax-app）的工程配置会对其，目前来看主要以 icejs 为主即可。应用级别的配置能力已经对其。iceworks 在设计和实现上应该不需要实现两份。

**Comment by sspku-yqLiu** [comment]
> 预计在 8 月下旬 icejs&raxjs（rax-app）的工程配置会对其，目前来看主要以 icejs 为主即可。应用级别的配置能力已经对其。iceworks 在设计和实现上应该不需要实现两份。

这意味着未来 rax-app 的配置在未来与 icejs 完全相同吗？ 这样的话似乎实现一份就可以了。
另外，例如 mpa 路由问题修复等可能会使得配置简化，暂时会有比较大的配置更新吗？

**Comment by sspku-yqLiu** [comment]
- [ ] 添加 rax/app.json 的 JSON SCHEMA 。

- [ ] 更新 ice/build.json  的 JSON SCHEMA。

- [ ] 使用 JSON Schema Form 制作 Web View。

- [ ] 实现对于 JSON 的动态更新

- [ ] 实现插件端代码，并完成双向通信

- [ ] 调整页面样式，进行 Code Review

**Comment by alvinhui** [comment]
主标题字体颜色：#e7e7e7
描述字体颜色：rgba(204, 204, 204, 0.9)
控件选中的边框颜色：#007fd4

**Comment by sspku-yqLiu** [comment]
#376

**Comment by sspku-yqLiu** [comment]
#380

**Comment by alvinhui** [comment]
https://github.com/ice-lab/iceworks/pull/401
