### ISSUE TITLE
代码补全和悬停信息记录 DAU

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#357]
### 问题描述

目前 React Style Helper 和 React Component Helper 插件所提供的代码补全和悬停信息功能均未记录 DAU，该部分需要进行 DAU 记录。

### 建议的解决方案

将 Logger 封装为可独立于 VS Code 运行的数据采集工具，在**代码补全和悬停信息有值**时，进行 DAU 记录。

> 目前 [Logger](https://github.com/ice-lab/iceworks/blob/master/packages/common-service/src/log.ts) 依赖 vscode.context.globalState

**Comment by fyangstudio** [comment]
#369
