### ISSUE TITLE
国际化方案（vscode插件+国际化库）加入飞冰生态

### ISSUE THREAD

**Issue by lirongfei123** [ice-lab/iceworks#365]
### 问题描述

本人所在团队摸索出一套没有任何痛点的国际化方案，希望加入飞冰生态

### 建议的解决方案
https://marketplace.visualstudio.com/items?itemName=rongpingli.react-intl-universal

### 解决的国际化问题
1. 解决代码做了国际化后，可读性降低的问题
2. 解决书写国际化的繁琐问题
3. 解决容易遗漏国际化的问题

### 附加信息

欢迎有志之士一起共建

**Comment by alvinhui** [comment]
目前 icejs 没有国际化方案， @chenbin92 看看是否可以加入这个章节？

Iceworks 这边可以作为附加的推荐插件，但文档上期望整理一下格式，具体我这边会再提要求。

**Comment by alvinhui** [comment]
@lirongfei123 目前规划上，我们不会在套件中添加面向单个垂直领域的第三方插件，如果插件质量 OK 可以在文档中推荐。

国际化方案的推荐请提 issue 到 https://github.com/alibaba/ice
