### ISSUE TITLE
组件开发辅助

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#396]
## 需求

在用户编写 UI 代码时更快地查找到相应组件的文档。

方式一：

1. 在 JSX 文件内，将光标聚焦到组件标签下（或选中组件标签）
2. 按下快捷键 `ctrl + cmd + z`
3. 激活一个标签页，显示该组件的文档

方式二：

1. 在 JSX 文件内，将光标聚焦到组件标签下
2. 在浮出的信息框下添加 “文档” 链接
    ![image](https://user-images.githubusercontent.com/4392234/89501751-78647e80-d7f6-11ea-9d9d-03ecbf278907.png)
3. 点击文档链接
4. 激活一个标签页，显示该组件的文档

方式三：

1. 按下快捷键 `⇧⌘P` 激活命令面板
2. 在命令面板输入：Iceworks: 查找组件
3. 弹起组件选择列表 
    ![image](https://user-images.githubusercontent.com/4392234/89501563-1c015f00-d7f6-11ea-81e2-72786967ab6f.png)
4. 选中某个组件
5. 激活一个标签页，显示该组件的文档

#### 说明

- 三种方式只实现一种方式即可
- 组件范畴：用户配置的物料源信息
    - 例如，PC Web 的业务组件：`@icedesign/*`，无线跨端的业务组件：`rax-*`
    - 额外需实现内置的的基础组件`@alifd/next`
- 组件文档页是在线的

## PR 说明

- 请基于 release/0.5.0 拉取开发分支
- 请将 PR 指向 release/0.6.0

## PR 要求

- 时间：下周三前提交 PR ，下周四早上合并入 Release 分支
- 质量：两轮 Review 后可 Merge 入 Release 分支

**Comment by sspku-yqLiu** [comment]
## 调研

### 方式

- 似乎方式 1 （快捷键唤醒） 与方式 2 （悬停提示） 的技术实现应该是差不多的，通过 vscode 提供的document 中的能力： getWordRangeAtPosition 即可获得组件标签，之后生成链接并使用文档打开。
- 方式三可能比较简单，而且打开的方式稍微有些复杂，是否可以通过像可视化面板那种在「特定的文件（jsx,tsx) 标题」提供 icon 进行唤醒呢？
- 我会先以方式二进行开发，如果时间充裕的话会将三种方式都实现。

### 思路

1. 通过 material -service 中提供的 getSourcesByProjectType 能力获取组件库物料源信息。

2. 使用自带的文档 url 或者根据不同的物料源生成文档 url 例如 ：

   - fusion 组件： https://fusion.design/pc/component/basic/${组件名称}
   - Rax 组件 https://github.com/raxjs/rax-components/tree/master/packages/rax${组件名称}
   - ice 组件：https://ice.work/component/${组件名称}
   - Ice 业务组件：https://unpkg.com/@icedesign/${组件名称}@${版本号}/build/index.html
   - Ice 区块 ：https://github.com/alibaba-fusion/materials/tree/master/blocks/${区块名称}

3. 由于 vscode 面板不能直接打开在线网页，所以这个问题比较麻烦，我看了两个在线网页的实现：

   - 例如：`elementUI-Helper` 尽管它看起来像是打开了一个在线网页，但是实际上他的实现是这样的

     ```ts
     return `    
     ...
     	<iframe id="docs-frame" src="${iframeSrc}"></iframe>
     ...
     `
     ```

     那么这个 iframeSrc 在哪里呢？

     ``` ts
     const iframeSrc = 'file://' + Path.join(Resource.ELEMENT_PATH, componentPath).split(Path.sep).join('/');
     static ELEMENT_PATH: string = Path.join(__dirname, '..', '..', 'node_modules', 'element-gh-pages');
     ```

     所以他展示的是 iframeSrc 中的一个网页包，这个网页与官网是同步的，因此「看起来像是打开了一个在线网页，实际上打开的是静态网页」

     这个网页包实际上只有一个 main.html 我更倾向于认为他把整个网站打包后放在了包中，这样他就可以实现跳转等操作。

   - 另一个例子：`leetcode`

     ``` ts
     this.extRoot = path.join(vscode.env.appRoot, "extensions", "markdown-language-features");
     ```

     也是使用本地文件来进行加载的。

   **可能需要像 element-ui-helper 一样使用网站源码来模拟打开在线网页。目前通过 iframe 打开了远程网页，存在以下几个问题：**

   - 单独打开网页 iframe 加载很快，放入 vscode 中加载很慢 大概需要 2-3 秒。

   - 无法控制 iframe 的高度 (需要使用 js 获取高度等操作)。
   - 可以访问 ice 物料库，访问 fusiondesign 被拒绝。

   我会尝试解决现存的问题。

### 重点

- 本次实现将更加关注代码的可读性以及健壮性。
- 本次实现将尽可能使用 iceworks 或社区已经存在的能力。

### 更进一步

- 为 TSX 文件提供相同的能力。（有可能完成）
- 提供一个小型窗口 (treeview) 告知用户使用了那些组件，并且可以通过右键？ 或者点击的形式进行跳转或打开窗口（需要在基本功能大幅提前完成时才能完成，需要使用 [acron](https://github.com/acornjs/acorn-jsx) (目前 react 使用的 jsx 解析器)

### 问题：

- 方式三可能比较简单，而且打开的方式稍微有些复杂，是否可以通过像可视化面板那种在「特定的文件（jsx,tsx) 标题」提供 icon 进行唤醒呢？
- 我应该在 material-helper 插件上添加功能还是制作一个新的组件？

### 风险：

**可能需要像 element-ui-helper 一样使用网站源码来模拟打开在线网页。通过 iframe 获取网页有一些现存的问题。**

### 节点：

我会在今晚完成一个小型 demo ,并提出一个 WIP PR。

工作节点计划将出现在 WIP 的 PR 中。

**Comment by alvinhui** [comment]
## 方式

方式三可能比较简单，而且打开的方式稍微有些复杂，是否可以通过像可视化面板那种在「特定的文件（jsx,tsx) 标题」提供 icon 进行唤醒呢？

> 标签栏按钮太多了，我们不建议再往上面添加图标

我会先以方式二进行开发，如果时间充裕的话会将三种方式都实现。

> 从实现难度来说 2 > 1 > 3；从对用户体验来说 2 > 3 > 1 。我会建议实现方式 3

## 思路

1. 调用 getSourcesByProjectType 的思路没有问题。source 内有文档的链接（参考 components 下的 homepage 字段）：

    https://ice.alicdn.com/assets/materials/react-materials.json
2. 用 iframe 的思路没有问题，兜底方案有两种。**优先确保兜底方案可行**。
   1. 依赖 [browser preview](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) 插件，用其来打开网页
   2. 直接调用浏览器打开网页

## 更进一步

没看懂。

## 问题

我应该在 material-helper 插件上添加功能还是制作一个新的组件？

> 在 material-helper 插件上添加功能

**Comment by sspku-yqLiu** [comment]
> 标签栏按钮太多了，我们不建议再往上面添加图标
> 从实现难度来说 2 > 1 > 3；从对用户体验来说 2 > 3 > 1 。我会建议实现方式 3

在实际制作 demo 的过程中我发现 2 是最难的，同意先使用3实现。

> ## 更进一步
> 没看懂。

我会在时间充裕的前提下制作一个小型 demo.

**Comment by sspku-yqLiu** [comment]
#405
