### ISSUE TITLE
iceworks初始化的物料库，多包场景希望增加lerna支持

### ISSUE THREAD

**Issue by imsobear** [ice-lab/iceworks#4]
目前使用iceworks生成物料库及component的模板代码生成，基于build-scripts做工程构建。多数场景物料库是一个多组件的场景（多npm包），其中不乏多包依赖的问题。目前的这个工程套件没有支持lerna，在做包管理比较低效，希望增加lerna多包管理能力。

需求来自 @hipoyang

**Comment by alvinhui** [comment]
https://github.com/ice-lab/iceworks-cli/issues/1
