### ISSUE TITLE
支持所有 JSON 文件的可视化配置

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#403]
### 需求描述

当前 Iceworks config helper 插件可以对 app.json 和 build.json 进行可视化配置，将此功能拓展到可对所有的 JSON 文件进行可视化配置。

产品交互参考 VS Code 对 Markdown 文件的处理：

1. 在资源管理器中，对 .json 文件右键，右键列表中添加「可视化配置」选项，点击该选项打开可视化配置页面，配置对应的 JSON 文件：
    ![image](https://user-images.githubusercontent.com/4392234/89629096-d749f680-d8cf-11ea-98d4-e8be2c8f9842.png)
2. 在标签栏右侧，显示配置图标，点击该图标打开可视化配置页面，配置对应的 JSON 文件：
    ![image](https://user-images.githubusercontent.com/4392234/89629151-ee88e400-d8cf-11ea-8142-9d52e1e11473.png)

## PR 说明

- 请基于 release/0.5.0 拉取开发分支
- 请将 PR 指向 release/0.6.0

## PR 要求

- 时间：下周四前提交 PR ，下周五早上合并入 Release 分支
- 质量：两轮 Review 后可 Merge 入 Release 分支

## 参考

对于没有 Schema 的 JSON 文件，可以通过对当前 JSON 文件的解析，生成 Schema。

即输入 `{ a: 1, b: 'string', c: true }`），输出：

```json
{
    "type": "object",
    "description": "file path",
    "properties": {
        "a": {
            "type": "integer",
            "description": ""
        },
        "b": {
            "type": "string",
            "description": ""
        },
        "c": {
            "type": "boolean",
            "description": ""
        }
    },
    "title": "file name"
}
```

**Comment by sspku-yqLiu** [comment]
### 调研

#### 关于 json schema 的生成

社区实现： https://github.com/nijikokun/generate-schema

**Comment by sspku-yqLiu** [comment]
#416
