### ISSUE TITLE
在可视化配置标签页显示源图标

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#404]
### 问题描述

当前可视化配置页面打开后，无法快速定位到源文件：

![image](https://user-images.githubusercontent.com/4392234/89635427-89d28700-d8d9-11ea-8fc5-17b74cb9cdc2.png)

参考 Markdown 预览模式的处理，在标签栏右侧添加显示源图标：

![image](https://user-images.githubusercontent.com/4392234/89635493-a53d9200-d8d9-11ea-83de-30a11f110ea4.png)

**Comment by sspku-yqLiu** [comment]
#416
