### ISSUE TITLE
transform-ts-to-js 迁移和相关内容补充

### ISSUE THREAD

**Issue by luhc228** [ice-lab/iceworks#433]
- bug: 生成 js 代码中有多余的内容 
![image](https://user-images.githubusercontent.com/44047106/90325008-a1c89b80-dfa8-11ea-910a-653e17b12e4a.png)

- 从 iceworks/packages 中移出，新建 repo 放到 ice-lab 中
- 补充相关文档
- 补充单测

**Comment by alvinhui** [comment]
https://github.com/ice-lab/iceworks/pull/641
