### ISSUE TITLE
能否为下载私有库zip包的时候，添加一个 token 配置？

### ISSUE THREAD

**Issue by hubingliang** [ice-lab/iceworks#443]
* 插件名：Iceworks ui builder
* 插件版本：v0.1.5

## 您的本地环境信息？

* 操作系统及其版本：mac
* Node 版本：10.21.0
* npm 版本：6.14.6

**Comment by luhc228** [comment]
你的私有库zip包是指？

**Comment by hubingliang** [comment]
是这样的我在用我们公司的私有库源下载物料组件时 报了401 然后我发现是 ice-npm-utils 这个包的 getAndExtractTarball 方法调用时 request 没有传 header 我自己加了一下就好了 所以能提供一个可自定义的 vscode 配置 加上这个 token 嘛

**Comment by imsobear** [comment]
@hubingliang header 要加什么？为什么要加？

之前有出现过一个需求，是希望支持配置 proxy，感觉有点类似？

**Comment by hubingliang** [comment]
![image](https://user-images.githubusercontent.com/23694644/90709677-4ca1c800-e2cf-11ea-880d-c695fbd4abc0.png)
类似这种，token 提供一个配置传进来 ，如果不加现在的情况就是这里报 401 因为我们公司的私有库必须传一个 token 才能访问

**Comment by imsobear** [comment]
确定下「私有 npm 源需要传 token 是不是一个标准的做法」，包括这个 headers 里的 key 命名是不是标准？如果是的话，我们可以看下怎么支持，如果不是的话建议跟搭私有 npm 源的同学讨论下这块是怎么考虑的。

**Comment by hubingliang** [comment]
1. 我们是用 Nexus3 搭建的 npm 私有库 应该算是比较通用的做法，确实是需要 token 才能访问。
2. 这个 key name 肯定是标准的：
首先是这个 mdn 的解释 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Authorization
其次其实你们之前的方法也涉及到需要传 token 的情况 比如 getTarballURLByMaterielSource 这个方法，不过它内部用了 packageJSON 这个来发起请求。packageJSON 内部依赖了 registry-auth-token 来从 .npmrc 文件里面拉取 token 所以其实只要写好 .npmrc 就不需要手动传了，但是 getAndExtractTarball 请求是用了 request-promise 这样的话就没办法拿 token 了。

**Comment by luhc228** [comment]
> 2\. getAndExtractTarball

欢迎 PR 或通过钉钉联系我们

**Comment by luhc228** [comment]
> 1. 我们是用 Nexus3 搭建的 npm 私有库 应该算是比较通用的做法，确实是需要 token 才能访问。
> 2. 这个 key name 肯定是标准的：
>    首先是这个 mdn 的解释 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Authorization
>    其次其实你们之前的方法也涉及到需要传 token 的情况 比如 getTarballURLByMaterielSource 这个方法，不过它内部用了 packageJSON 这个来发起请求。packageJSON 内部依赖了 registry-auth-token 来从 .npmrc 文件里面拉取 token 所以其实只要写好 .npmrc 就不需要手动传了，但是 getAndExtractTarball 请求是用了 request-promise 这样的话就没办法拿 token 了。

欢迎 PR 或通过钉钉联系我们

**Comment by luhc228** [comment]
不清楚具体实际的场景，先 close 该 issue
