### ISSUE TITLE
官方项目添加 VS Code 插件推荐

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#458]
### 问题描述

VS Code 提供了打开一个工作区时，推荐用户安装插件的功能：

![image](https://user-images.githubusercontent.com/4392234/91151286-0f36a380-e6f0-11ea-80b6-b8e4f195fa10.png)

实现方式是项目内有 .vscode/extensions.json，内容：

```json
{
	"recommendations": [
		"iceworks-team.iceworks"
	]
}
```
See https://go.microsoft.com/fwlink/?LinkId=827846 for the documentation about the extensions.json format

### 建议的解决方案

以下项目添加 .vscode/extensions.json

- [x] 物料项目初始化模板：https://github.com/ice-lab/material-templates @alvinhui 
- [x] PC Web 模板：https://github.com/alibaba-fusion/materials @luhc228 
- [x] 无线跨端模板：https://github.com/raxjs/rax-materials @fyangstudio 
- [x] 小程序模板：https://github.com/ice-lab/miniprogram-materials @luhc228

**Comment by fyangstudio** [comment]
ok
