### ISSUE TITLE
侧边栏相关功能根据应用类型显示或隐藏

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#468]
### 问题描述

1. 当用户在开发 Rax 应用时，不显示「可视化搭建组件」功能，该功能当前对 Rax 应用不可用；
2. 当用户开发开发天马模块应用时，不显示「页面」和「组件」列表以及其他对天马模块不可用的功能。

### 建议的解决方案

在 project-service 添加一个 isPegasusProject 的方法，判断是否天马模块。

**Comment by luhc228** [comment]
已发布 release/0.8.0 解决
