### ISSUE TITLE
欢迎页

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#471]
创建应用完成或首次打开应用，弹出「欢迎页」，引导用户继续进行使用 Iceworks。

![image](https://user-images.githubusercontent.com/4392234/91379250-d49a4b80-e854-11ea-862f-f3183a07ae2f.png)

欢迎页包含的内容：

- 视频介绍列表（需要明确列表包含哪些内容）
- 问题反馈入口

**Comment by luhc228** [comment]
视频内容列表

- 快速创建应用
-  搭建应用（项目大纲树演示、调试构建操作、快速搭建页面和组件、添加组件）
- 编码辅助
- 使用自定义物料

**Comment by alvinhui** [comment]
> 视频内容列表
> 
> * 快速创建应用
> * 管理应用依赖（重装依赖、新增依赖、升级依赖、配置镜像源）
> * 搭建应用（调试构建操作、快速搭建页面和组件、添加组件至源码中）
> * 使用编码辅助
> * 使用自定义物料


- 创建应用：设置管理应用依赖、执行 npm 脚本、设置客户端和镜像源
- 可视化开发：添加组件、区块、区块组装页面、模板生成页面
- 使用自定义物料源：设置物料源、创建应用、可视化开发内容
- 发布应用：调试构建、发布
