### ISSUE TITLE
Rax 搭建页面产物错误

### ISSUE THREAD

**Issue by fyangstudio** [ice-lab/iceworks#506]
![image](https://user-images.githubusercontent.com/9896768/92087019-92957a80-edfd-11ea-87a7-c2aa2874eb26.png)
![image](https://user-images.githubusercontent.com/9896768/92087044-9b864c00-edfd-11ea-92cf-ba181fbe7789.png)

生成了 React 的代码，应该生成 Rax 的代码。

```
import React, { Component } from 'react';
// 应替换为
import { createElement} from 'rax';
```

**Comment by luhc228** [comment]
使用Create Page添加 page 的时候，routes.ts 会忽略用 lazy 引入的原页面，又重新 import 了一遍

![image](https://user-images.githubusercontent.com/44047106/92425842-f67fc080-f1ba-11ea-82c6-3c1e47012d60.png)

**Comment by alvinhui** [comment]
release 0.9.2
