### ISSUE TITLE
RFC: Iceworks 创建应用时支持可视化定制模板

### ISSUE THREAD

**Issue by luhc228** [ice-lab/iceworks#511]
考虑到大部分场景下主要有一个 Layout，因此可以先支持搭建一个 BasicLayout。

在创建应用的第一步中，点击添加自定义模板的按钮，以开始创建自定义模板：
![image](https://user-images.githubusercontent.com/44047106/95967212-9544b000-0e3e-11eb-8878-6c32debd4ad0.png) 

支持配置主题包、高级配置（代码实践示例）、为当前模板添加页面（菜单）和其他组件：
![image](https://user-images.githubusercontent.com/44047106/95967352-bc9b7d00-0e3e-11eb-8c01-324871a351ac.png)

点击『添加』按钮，唤起弹窗，可以通过区块组装页面：
![image](https://user-images.githubusercontent.com/44047106/96069981-df2aa600-0ed1-11eb-9302-8706d413dce2.png)

后续：
- 支持创建多个 Layout

**Comment by alvinhui** [comment]
前置流程没有说明，是选择了一个模板后进行配置还是？

**Comment by alvinhui** [comment]
这里也可以看一下：

- 是在物料项目开发的时候，帮助更好地生成脚手架，
- 还是在应用开发的时候可视化定制模板

前者能够提升模板的开发效率并且使得模板在更大范围进行流通，后者是一次性的。

**Comment by luhc228** [comment]
> 前置流程没有说明，是选择了一个模板后进行配置还是？

在创建应用的流程中，是先选择了一个模板后进行配置的
上面的 issue 已经修改补充了

**Comment by luhc228** [comment]
> 这里也可以看一下：
> 
> * 是在物料项目开发的时候，帮助更好地生成脚手架，
> * 还是在应用开发的时候可视化定制模板
> 
> 前者能够提升模板的开发效率并且使得模板在更大范围进行流通，后者是一次性的。

这里上面的两点建议都很好，都可以支持。优先级的话，我认为先支持第二个，再支持第一个。
