### ISSUE TITLE
配置模板生成页面产物错误

### ISSUE THREAD

**Issue by luhc228** [ice-lab/iceworks#516]
关闭其中的配置项，生成的产物依然存在
![image](https://user-images.githubusercontent.com/44047106/92427599-6f811700-f1bf-11ea-8e2d-e7324764bb4c.png)

![image](https://user-images.githubusercontent.com/44047106/92427637-8fb0d600-f1bf-11ea-9d69-924f4e4ff8db.png)

**Comment by alvinhui** [comment]
没有错呀？其他登录方式对应的是右下角的东西。
