### ISSUE TITLE
物料相关功能优化

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#541]
- [x] 允许指定生成代码的路径：优先级和逻辑需梳理。
    - 有指定时，生成到该路径
    - 当没有指定时：
        - 是支持的项目类型时，生成到指定位置
        - 不支持的项目类型时，弹出本地文件夹选项，让用户选择指定的位置
- [x] 物料面板：
    - [x] 没有打开代码编辑器时，提示无法唤起物料面板；
    - [x] 添加区块可以添加到任何的视图文件(jsx/tsx/vue)。

**Comment by luhc228** [comment]
- 梳理**可配置**生成代码位置
    - 页面生成的位置
    - 组件生成的位置
    - 可视化搭建的组件生成的位置
