### ISSUE TITLE
增加环境配置后，在build.json区分工程配置后，打包失败问题

### ISSUE THREAD

**Issue by jadestarzuo** [ice-lab/iceworks#549]
package.json中，打包增加环境配置后"build:prod": "icejs build --mode prod"
build.json中也要对应增加区分工程配置，如：使用文档上所示：
{
  "alias": {},
  "modeConfig": {
    "daily": {
      "define": {},
      "vendor": false
    },
    "prod": {
      "define": {},
      "vendor": true,
      "plugins": ["build-plugin-esbuild"]
    }
  }
}

执行npm run build:prod 会报错
TypeError: userConfig.plugins is not iterable

需要在build.json中加一段： "plugins": [], 

{
 "plugins": [], 
  "alias": {},
  "modeConfig": {
    "daily": {
      "define": {},
      "vendor": false
    },
    "prod": {
      "define": {},
      "vendor": true,
      "plugins": ["build-plugin-esbuild"]
    }
  }
}

**Comment by alvinhui** [comment]
请将这个问题提交到 https://github.com/alibaba/ice/issues

@ClarkXia
