### ISSUE TITLE
vue支持

### ISSUE THREAD

**Issue by cereschen** [ice-lab/iceworks#558]
### 问题描述

目前对vue的支持不够

### 建议的解决方案

样式  Completion  hover  触发条件添加 class 目前只有className,
页面列表和组件列表目前仅指向 pages and components 目录  建议可配置 以支持老项目

**Comment by alvinhui** [comment]
当前我们对 Vue 的支持，精力有限，不会主动提供，这方面欢迎社区进行共建。

- 第一个问题没看明白， @fyangstudio 能理解吗？
- 第二个问题已有一个 issue 进行跟踪：https://github.com/ice-lab/iceworks/issues/541

**Comment by cereschen** [comment]
> 当前我们对 Vue 的支持，精力有限，不会主动提供，这方面欢迎社区进行共建。
> 
> * 第一个问题没看明白， @fyangstudio 能理解吗？
> * 第二个问题已有一个 issue 进行跟踪：#541

不好意思 之前表述的不太清晰
以图为例 这里使用className可以触发 css文件里的定义
![image](https://user-images.githubusercontent.com/52478109/93663073-a09ef880-fa97-11ea-84c6-5042ba9d46e1.png)

但是一些其他的框架或许用的是class属性 例如vue3
```jsx
<div  class="" >{props.name}</div>
```
在这样的情况下不会触发提示

**Comment by alvinhui** [comment]
我们将在 v0.11.0 版本中修复此问题，v0.11.0 版本将在下周一发布。
