### ISSUE TITLE
 english language version

### ISSUE THREAD

**Issue by jimrandell** [ice-lab/iceworks#574]
from what I can see this looks great!but I cant use it, I don't understand the label text.
any plans on an english version?
![SNAG_Program-0002](https://user-images.githubusercontent.com/3543506/94052290-a3b82280-fdd0-11ea-9fcf-4031efcc73e8.png)

**Comment by alvinhui** [comment]
@youluna @bindoon I think the material center needs to add internationalization to the daily planning.

**Comment by alvinhui** [comment]
for this case, maybe check schema(config/settings.json) how to support i18n. @sspku-yqLiu

**Comment by sspku-yqLiu** [comment]
OK, I'm trying to update this in next version

**Comment by sspku-yqLiu** [comment]
It seems that Formily does not provide i18n function .so here is two plans to implement i18n in JSON SCHEMA:
- Use object in all places need i18n, like:
    ```json
    "properties": {
      "uri": {
        "key": "uri",
        "x-component": "input",
        "type": "string",
        "title": {
          "zh-CN": "资源请求地址",
          "en-US": "SOURCE URL"
        },
        "x-component-props": {
          "placeholder": {
            "zh-CN": "请输入资源地址",
            "en-US": "Please Enter Source URL"
          },
          "addonTextBefore": "",
          "addonTextAfter": "",
          "trim": true,
          "hasClear": true
        },
        "children": []
      },
      ...
    }
- Or use addition properties:
    ```json
    "properties": {
      "uri": {
        "key": "uri",
        "x-component": "input",
        "type": "string",
        "zh-cn:title": "资源请求地址",
        "en-US:title": "SOURCE URL",
        "x-component-props": {
          "zh-CN:placeholder": "请输入资源地址",
          "en-US:placeholder": "Plese Enter Source URL",
          "addonTextBefore": "",
          "addonTextAfter": "",
          "trim": true,
          "hasClear": true
        },
        "children": []
      },
      ...
    }
- Or use languagePackages:
    ```json
    "i18n": true,
    "properties": {
      "uri": {
        "key": "uri",
        "x-component": "input",
        "type": "string",
				"title": "uri.title"
        "x-component-props": {
          "placeholder": "uri.placeholder",
          "addonTextBefore": "",
          "addonTextAfter": "",
          "trim": true,
          "hasClear": true
        },
        "children": []
      },
      ...
    }
    ...
    // config/locale/zh-CN.json
    {
    	"uri.title": "资源请求地址"
    	"uri.placeHoder": "请输入资源地址"
    }
    
    // config/locale/en-US.json
    {
    	"uri.title": "SOURCE URL"
    	"uri.placeHoder": "Plese Enter Source URL"
    }
    ```

These schemas will convert into formily schema before loading, then ui-builder supports i18n

**Comment by alvinhui** [comment]
use language packages is better @sspku-yqLiu

**Comment by alvinhui** [comment]
or maybe submit a issue to Formily, @janryWang can help

**Comment by jimrandell** [comment]
> It seems that Formily does not provide i18n function. so here are three plans to implement i18n in JSON SCHEMA:
> * Use object in all places need i18n:
> * Or use addition properties:
> * Or use language packages:
> These schemas will convert into formily schema before loading, then ui-builder supports i18n

thank you, I might give that a try. can you provide the exact names of all the  files to edit, and their relative paths paths?

**Comment by sspku-yqLiu** [comment]
> > It seems that Formily does not provide i18n function. so here are three plans to implement i18n in JSON SCHEMA:
> > 
> > * Use object in all places need i18n:
> > * Or use addition properties:
> > * Or use language packages:
> >   These schemas will convert into formily schema before loading, then ui-builder supports i18n
> 
> thank you, I might give that a try. can you provide the exact names of all the files to edit, and their relative paths paths?

Hi, these forms are used to creating pages. Material developers building PAGE TEMPLATES and CONFIGURATION FORMS, then we can easily creating pages through forms.
Youre looking at CONFIGURATION FORMS, unfortunatly, these forms didnt provide I18n yet. So we are discussing a way for it. After material developers provide I18n CONFIGURATION FORMS, you can understand these labels. you need to wait since we are during Nations Day, material developers are in vacation until 9 October.

If you are interested in materials, have a look at offical material repository: https://github.com/alibaba-fusion/materials.

An Example of JSON SCHMA : https://github.com/alibaba-fusion/materials/blob/master/pages/UserLogin/config/settings.json
