### ISSUE TITLE
开发效率报告 - Time Master

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#594]
## 一、背景和目标

广义的**研发效率**是指软件从需求到上线的完整过程中的投入和产出比。**开发效率**即编程效率，是指**单位时间内有效的代码产出**。开发效率是研发效率的重要组成部分。

我们通过定义开发效率的评估标准，产出团队的开发效率报告，分析影响开发效率的因素，制定提升开发效率的方案，对方案进行实施，观测效率数据变化，调整提效方案，**最终达到提升个人和团队开发效率的目的**。

![image](https://img.alicdn.com/tfs/TB1zvjkkzMZ7e4jSZFOXXX7epXa-622-642.png_290x10000.jpg)

本方案关注**如何产出开发效率报告**，涉及到**开发效率的评估**、**数据的采集**和**数据的报告**三个方面的设计。

## 二、整体方案

![image](https://img.alicdn.com/tfs/TB1xNAYliDsXe8jSZR0XXXK6FXa-680-204.png)

- **开发者**：实际编程角色
- **编辑器**：开发使用的编程工具，用于产出代码
- **编程数据采集客户端**：作为编辑器的组件（插件）集成到编辑器中，采集开发者的编程行为及时间
- **编程行为数据库**：存放采集客户端上报的编程行为及时间数据
- **计算平台**：实时或离线从编程时间数据库获取数据条目，进行数据筛选、计算，产出报表数据到编程时效数据库
- **编程时效数据库**：存放经过处理的编程时间及效率报表数据
- **数据报告平台**：从编程时效数据库获取数据并可视化展示
- **管理者**：可访问报告平台的角色

## 三、效率评估：度量模型设计 

开发效率(Efficiency) = 开发时间(Time) / 软件复杂度(Complexity)。值越小，说明效率越高。
设开发效率为 E，开发时间为 T，软件复杂度为 C，则有：

![image](https://user-images.githubusercontent.com/4392234/94543995-4cf19380-027d-11eb-8766-359630e2569f.png)

> 备注：需同时考虑代码质量 Q

设计算开发时间的函数为 `calTime`，计算软件复杂度的函数为 `calComplexity`，函数计算逻辑如下。

### 计算开发时间

开发时间分为两个粒度：

- 编程时间(Code Time)：是指在编辑器中花费的总时间。
- 活跃编程时间(Active Code Time)：是指编辑器中键入用的总时间。

> 活跃编程时间是总编程时间的子集。

##### 编程时间

公式一，设计算时间段的开始时间为 t0，结束时间为 t1，打点间隔时间量为 d，编辑器是否聚焦为条件 f(x)，则有计算时间段内的编程时间量为 C 为：

![image](https://user-images.githubusercontent.com/4392234/96238391-00be8700-0fd1-11eb-8215-7b31ad1db25d.png)

公式二，设每次聚焦窗口时间点为 F，离开窗口时间为 L，总次数为 k，则有计算时间段内的编程时间量为 C 为：

![image](https://user-images.githubusercontent.com/4392234/96239140-ee911880-0fd1-11eb-9246-bf9b687d1f17.png)

##### 活跃编程时间

设计算时间段的开始时间为 t0，结束时间为 t1，打点间隔时间量为 d，打点时间间隔内开始变更文本时间为 s0, 结束变更文本时间为 s1，则有计算时间段内的活跃编程时间量 AC 为：

![image](https://user-images.githubusercontent.com/4392234/96237061-6e69b380-0fcf-11eb-88ae-8f82b20578a1.png)

> 该公式为保证效率牺牲了准确性

#### 参考 VS Code API

- window.state.focused 窗口是否聚焦
- window.onDidChangeWindowState 窗口状态改变后触发的回调
- workspace.onDidOpenTextDocument 打开文本文件后触发的回调
- workspace.onDidCloseTextDocument 关闭文本文件后触发的回调
- workspace.onDidChangeTextDocument 更新文本文件后触发的回调

#### 计算方式

开发时间 = 单个时间周期内的总编程时间。

可以以「天」或「一次迭代」为周期得出在该周期内：

- 在某个文件内的编程时间
- 在某个项目的编程时间
- 总的编程时间

#### 计算公式

使用霍尔斯特德复杂度量测（Halstead Complexity Measures）。

![image](https://user-images.githubusercontent.com/4392234/94544479-df923280-027d-11eb-9376-2a72b1124c65.png)

```typescript
type Effort = number;
type calComplexity = (source: string) => Effort;
```

#### 计算方式

软件复杂度 = 单个时间周期内所有变更文件的代码复杂度。

以一次迭代周期为例：

- 设初始代码为 0 个文件，本次迭代最终发布时新增 n 个文件，则软件复杂度为：

    ![image](https://user-images.githubusercontent.com/4392234/94553380-09058b00-028b-11eb-8ba5-13b8eb0a1e4f.png)
- 设初始代码为 n 个文件，本地迭代最终新增 a 个文件，删除 b 个文件，变更 c 个文件，则软件复杂度为：

    ![image](https://user-images.githubusercontent.com/4392234/94553408-13278980-028b-11eb-93f1-fe09b6b02d12.png)

### 开发效率的统计维度

根据公式，即可以得到某个时间周期内的开发效率。

#### 天/周……的开发效率

- **天** = 一天内的总开发时间/一天内变更文件的代码复杂度。
- **周** = 一周内的总开发时间/一周内变更文件的代码复杂度。
- 其他时间维度的开发效率亦同理可得。

#### 单次迭代的开发效率

**npm 包**：以包版本发布为一个迭代周期。

设当前发布时间点为 P1，上一次发布时间为 P0，时间点间变更的文件数为 n，则有：
    
- ![image](https://user-images.githubusercontent.com/4392234/94554051-0eafa080-028c-11eb-9dac-6956fcbed1de.png)
- ![image](https://user-images.githubusercontent.com/4392234/94554011-fccdfd80-028b-11eb-97e4-193b51bbac5c.png)
- ![image](https://user-images.githubusercontent.com/4392234/94543995-4cf19380-027d-11eb-8766-359630e2569f.png)

**项目**：以分支发布为一个迭代周期。

设当前分支合并到主干分支时间点为 P1， 当前分支拉取时间点未 P0，时间点间变更的文件数为 n ，根据上述公式可亦同理可得出 E。

## 四、数据采集：客户端设计

有了效率度量模型，我们需要在编辑器中实现编程数据采集，以供后续进行编程数据分析。

以插件的形式实现，然后集成到 VS Code、O2、WebIDE。

该插件不仅采集数据，也产出简单的数据报告，供用户进行参考。

### 提供的用户价值

- 开发者可了解自己每天的编程效率如何；
- 开发者可了解一天中编程效率最高的时间段是什么时候，帮助开发者合理安排编程时间。

### 提供的核心差异

- 关注效率而不仅仅是编程时间花费；
- 完全本地化（90 天），可以不依赖网络，开放数据连接层，可对接任意的线上平台。

### 原型图

![image](https://user-images.githubusercontent.com/4392234/94578110-e3d44500-02a9-11eb-94de-ac43d6d33a4c.png)

**Iceworks 侧边栏**添加「效率报告」和「实时效率」两个视图：

- **效率报告**视图，包含以下行动点：
    - 数据大盘：仅面向内网用户，点击后跳转到个人线上开发效率数据大盘
    - 个人总结：点击后打开新标签，显示个人文字版的效率报告，包括今天、昨天、上周、近 90 天的效率详情；近 90 天效率平均值。
    - 项目总结：点击后打开新标识，显示个人在该项目的文字版的效率报告
- **实时效率**视图，包含以下选项：
    - 效率评分：今天、昨天、平均
    - 编程时间：今天、昨天、平均
    - 活跃编程时间：今天、昨天、平均（非实时计算，需要手动刷新）
    - 添加代码行：今天、昨天、平均
    - 删除代码行：今天、昨天、平均
    - 按键输入：今天、昨天、平均
    - 更新文件：今天、昨天、平均
    - 单位时间输入最多的文件：前三名
    - 按键输入最多的文件：前三名
    - 编程时间投入最高的文件：前三名

**VS Code 右侧状态栏**添加今天的「活跃编程时间」数据，当今天数值超过平均水平时将出现提示图标。

### 技术方案

https://github.com/ice-lab/iceworks/pull/620

### 提供的用户价值

- 对于团队管理者，可以通过平台了解到团队整体和某个下属的效率情况和项目投入情况
- 对于个人开发者，可以通过平台可视化地看到自己过往所有的效率情况和编程投入情况

### 提供的核心差异

- 相对于客户端：数据是持久化和可视化展示的
- 相对于其他平台：主要关注编程时数据，显示效率和编程时间投入情况

#### 个人维度

与客户端的差别：客户端仅展示文字版本的数据报告，平台展示可视化版本的数据报告。

![image](https://img.alicdn.com/tfs/TB15iZXihvbeK8jSZPfXXariXXa-1587-3322.png)

#### 个人项目维度

![image](https://img.alicdn.com/tfs/TB1B_WDYUT1gK0jSZFrXXcNCXXa-2038-1922.png)

#### 团队维度

![image](https://img.alicdn.com/tfs/TB15rolWxz1gK0jSZSgXXavwpXa-2076-1792.png)

### 技术方案

- 客户端 => 离线数据库：发送 HTTP 请求，请求内容参考客户端设计章节中的《数据上报设计》
- 离线数据库 => 计算平台(D2) => 在线数据库：计算平台新建定时任务，每天凌晨从离线数据库拉取上一天的数据，计算后添加数据到在线数据库
- 在线数据库 => 数据报告平台：数据报告平台实时从在线数据库获取数据进行展示

#### 数据库设计

离线数据库：

![离线数据库](https://img.alicdn.com/tfs/TB1Knva0WL7gK0jSZFBXXXZZpXa-467-719.png)

- session_time: 活跃编程时间记录表
- editor_time: 编辑器使用时间记录表

在线数据库：

![在线数据库](https://img.alicdn.com/tfs/TB1_E36n8FR4u4jSZFPXXanzFXa-829-514.png)

## 六、整体计划

- 10 月底：客户端上线
- 11 月底：平台端上线

**Comment by fyangstudio** [comment]
* 公式名统一 + 说明
![image](https://user-images.githubusercontent.com/9896768/96964117-78923180-153c-11eb-9333-15e29e269a7a.png)
![image](https://user-images.githubusercontent.com/9896768/96964248-b727ec00-153c-11eb-9a07-0ad7fc022a89.png)
* 原型图
个人维度 
是不是展示的有点多，其他的 都应该上 墨刀 上补下。 我会补充 质量的交互。
* 数据库设计
   - 离线数据库 也应该有个 用户 和 项目的 关联表吧
   - 少了 团队 的表
