### ISSUE TITLE
VSCode无法使用Debug功能

### ISSUE THREAD

**Issue by Lucidniht** [ice-lab/iceworks#605]
当前VsCode版本是1.50.0，操作系统是Win10 Ver 19042.541
直接调试启动提示以下错误
![1](https://user-images.githubusercontent.com/722502/95648970-c4d97c80-0b0d-11eb-8330-25285bb4ddc2.png)

终端从powershell切换成cmd也是同样的错误，用管理员模式启动VsCode也不行。
直接在终端中使用npm run start -- --disable-open是可以正常进入开发模式，但只能在浏览器中调试。
非iceworks项目也能正常唤醒chrome进行调试。

----更新------
![2](https://user-images.githubusercontent.com/722502/95724395-e6bb3680-0ca8-11eb-9191-176e3d336874.png)
这里需要指定task type := shell, 默认是process。
以及停止调试后，npm这个后台任务也没有停止。

**Comment by fyangstudio** [comment]
vscode win10 terminal 错误 https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

**Comment by fyangstudio** [comment]
这部分功能已改成 预览，debug 功能已迁移至 文档:

https://github.com/ice-lab/iceworks/blob/master/extensions/iceworks-app/docs/debug.md
