### ISSUE TITLE
打开工作台，点击终端，显示功能不可用

### ISSUE THREAD

**Issue by zhangfeng993** [ice-lab/iceworks#64]
打开工作台，点击终端，显示终端断开连接（提示终止终端或重新连接终端）

![72587332-da7b9600-392f-11ea-9b6e-42a5d77127fb](https://user-images.githubusercontent.com/39079641/84009266-999b2100-a9a5-11ea-846b-e97f01fd8f86.png)

**Comment by alvinhui** [comment]
可以使用我们提供的 VS Code 套件：
https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks
