### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Waitingfml** [ice-lab/iceworks#661]
- Issue Type: `Performance`
- Extension Name: `iceworks-doctor`
- Extension Version: `0.1.7`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Waiting\AppData\Local\Temp\iceworks-team.iceworks-doctor-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alvinhui** [comment]
cpuprofile.txt 可以提供一下？

**Comment by fyangstudio** [comment]
#669

**Comment by fyangstudio** [comment]
0.2.0 已发布
