### ISSUE TITLE
componentgenerator源码

### ISSUE THREAD

**Issue by ltfund** [ice-lab/iceworks#664]
可视化搭建组件componentgenerator是开源的吗？项目中没有找到相关的代码
![image](https://user-images.githubusercontent.com/63779507/100176289-f4501700-2f0a-11eb-9de2-66f0461767ad.png)

**Comment by alvinhui** [comment]
搭建部分的源码目前没有开源，暂时也没有开源的计划。

**Comment by WilliamALiang** [comment]
今年有开源计划了没有
