### ISSUE TITLE
could not create project

### ISSUE THREAD

**Issue by dingjiakiss** [ice-lab/iceworks#673]
Issue Type: <b>Bug</b>

vs code could not open iceworks create project page

Extension version: 0.4.3
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.06GB free)|
|Process Argv|--crash-reporter-id ee520e31-d56f-433d-b6b7-c50458264322 --crash-reporter-id ee520e31-d56f-433d-b6b7-c50458264322|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by alvinhui** [comment]
could you [open the developer tool](https://stackoverflow.com/questions/30765782/what-is-the-use-of-the-developer-tools-in-vs-code) and see if there are any errors?

**Comment by luhc228** [comment]
Could you provide any recurrence steps?
