### ISSUE TITLE
创建应用时，点击设置按钮，自动弹出了「新增物料源弹窗」

### ISSUE THREAD

**Issue by caiyongmin** [ice-lab/iceworks#684]
插件名/Extension: iceworks-project-creator

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: OSX EI Capitan，版本 10.11(15A284)
* Node version: v10.23.0
* npm version: 6.14.8

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

如标题所示的复现步骤：
① 点击创建应用按钮。
② 点击设置按钮。
③ 设置界面打开，自动弹出「新增物料源弹窗」

![image](https://user-images.githubusercontent.com/11053605/101882533-fc79a900-3bd0-11eb-81b2-4f3b17669f6a.png)
![image](https://user-images.githubusercontent.com/11053605/101882844-642ff400-3bd1-11eb-94c5-041d5c942b0b.png)

## 您期待的正确结果/The right result you're looking forward to

打开设置面板时，不自动弹出「新增物料源弹窗」，因为这样阻断了用户的设置操作，用户一开始并不想新增物料源，所以用户需要先把弹窗关闭，再进行设置，给用户不必要的困扰。

## 您有建议的解决方案，亦可进行说明/If you have a suggested solution, you can also explain it.

通过阅读代码可以看到点击设置按钮，调用的是 `onOpenConfigPanel` 方法，它里面调用了 @iceworks/common-service  的 `openMaterialsSettings` 方法，这个方法作用就是在打开设置面板时自动弹出「新增物料源弹窗」。
所以点击设置按钮，不能调用这个方法，下面是我写的一个方法，如果觉得没有问题，我就提交一个 PR。
```ts
async function onSettingsClick() {
  try {
    await callService('common', 'executeCommand', 'iceworksApp.configHelper.start');
  } catch (e) {
    Notification.error({ content: e.message });
  }
}
```

**Comment by luhc228** [comment]
这里的功能设计应该是：
- 点击右上角的设置，进入设置面板，不自动弹出「新增物料源弹窗」
- 点击左下方的物料添加，进入设置面板，自动弹出「新增物料源弹窗」

**Comment by caiyongmin** [comment]
> 这里的功能设计应该是：
> 
> * 点击右上角的设置，进入设置面板，不自动弹出「新增物料源弹窗」
> * 点击左下方的物料添加，进入设置面板，自动弹出「新增物料源弹窗」

是的，同意，点击右上角的设置，进入设置面板，不自动弹出「新增物料源弹窗」
但是现在点击右上角的设置，进入设置面板，自动弹出来了「新增物料源弹窗」，所以有点问题
