### ISSUE TITLE
使用自定义物料时报错

### ISSUE THREAD

**Issue by s6-ht** [ice-lab/iceworks#685]
问题：
使用自定义物料时，publish成功后，生成的materials.json文件地址：https://unpkg.com/jy-material@0.1.5/build/materials.json

此时在iceworks中配置自定义物料源时，详细如下：
![image](https://user-images.githubusercontent.com/43433433/102035951-a8eba300-3dfc-11eb-8df7-c6ec9ca862d5.png)

然后使用自定义区块，报错如下：
![image](https://user-images.githubusercontent.com/43433433/102036076-e7815d80-3dfc-11eb-83b5-19957d26bfaa.png)

上图显示下载的url为空，请问这个url 是需要在哪里配置？

系统：mac/windows

**Comment by luhc228** [comment]
我这边试了一下，添加物料源成功，并且能正常显示出来

![image](https://user-images.githubusercontent.com/44047106/102037197-932bad00-3dff-11eb-9049-a40d5c2f4ab3.png)

**Comment by s6-ht** [comment]
步骤：
1. 选择使用区块生成页面
2. 能够正常的显示自定义区块
3. 点击添加区块到页面，添加成功。如图1；
4. 点击生成页面，出现该报错。如图2；

图1: 
![image](https://user-images.githubusercontent.com/43433433/102038256-bf482d80-3e01-11eb-9e6d-35fac8760b46.png)

图2: 
![image](https://user-images.githubusercontent.com/43433433/102037871-daff0400-3e00-11eb-808a-6e62158e2900.png)

配置：
我使用的项目模版为Vue materials 中的Admin Lite。对于接入自定义物料，我仅仅做了如下配置，请问还需要其它配置吗？
![image](https://user-images.githubusercontent.com/43433433/102037961-126db080-3e01-11eb-9ef4-85d5c80e386e.png)

**Comment by luhc228** [comment]
目前逻辑中，拉取物料源信息，是从[淘宝源](https://registry.npm.taobao.org/)中拉取的（在国内下载物料速度更快）：
https://github.com/ice-lab/iceworks/blob/60faf4a44d14c56ee525656a235a41c8eb96de43/packages/material-utils/src/methods.ts#L103

发布了物料之后，需要同步一下当前物料对应 npm 包到淘宝源（默认是10分钟同步一次的）。比如同步 `jy-block` npm 包：
https://npm.taobao.org/sync/jy-block

**Comment by s6-ht** [comment]
确实是还没有同步到淘宝源的问题，同步之后问题已经解决。非常感谢您～
