### ISSUE TITLE
O2 套件构建和发布的脚本和流程优化

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#697]
## 背景

预见 WebIDE 落地外包场景后需要频繁地发布 O2 套件以修复问题。

为提高发布流程的效率，需要引入自动化流程。

## 当前流程

参考：[O2 SPECIFIC](https://github.com/ice-lab/iceworks/blob/master/.github/O2_SPECIFIC.md)

在本地执行：

- `npm run o2:general`: 生成 o2 套件源代码
- `npm run o2:package`: 构建 o2 套件包

在 [MarketPlace](https://marketplace.alipay.com/extension/5f977bd57872c6d7e71f2794) 执行：

- 上传套件包
- 审核插件
- 上架插件

## 期望的流程

在 CI 中自动完成 O2 打包和上传流程： 

- 构建 O2 套件包
- 将 O2 套件包上传到 OSS

> 注意：构建 O2 套件包需要使用 @ali/kaitian-cli ，该包当前在内部 npm 源，在 Github CI 中无法使用

在本地运行一个命令，完成：

- 将 OSS 最新的套件包上传到插件市场
- 审核插件
- 上架插件

> 注意：该流程需要依赖 MarketPlace 的 API ，该 API 仅内网环境可访问。
> 因此无法在 Github CI 中调用，需要本地执行。

## 参考

- [MarketPlace API](https://yuque.antfin-inc.com/ide-framework/extension/vb2aa4)
- [@ali/kaitian-cli](https://yuque.antfin-inc.com/ide-framework/extension/ywgssg)

**Comment by luhc228** [comment]
构建 O2 套件包需要使用到的内部的 @ali/kaitian-cli npm 包，把这个 npm 包的压缩包放在 oss 上。在 github CI 流程中，下载压缩包，然后进行构建 O2 套件。

**Comment by alvinhui** [comment]
> 构建 O2 套件包需要使用到的内部的 @ali/kaitian-cli npm 包，把这个 npm 包的压缩包放在 oss 上。在 github CI 流程中，下载压缩包，然后进行构建 O2 套件。

可以的
