### ISSUE TITLE
希望扩展一下预览插件(Browser Preview)

### ISSUE THREAD

**Issue by xmsz** [ice-lab/iceworks#698]
其实就是想所有事都在VS Code中处理，不想再打开一个浏览器窗口，但是现在有些需求没办法满足

希望增加的功能
- 自定义UA，原来只有一个「假的」手机切换没有意义。希望可以有自定义UA的功能，这样就可以自己模拟环境了
- 自定义分辨率，和第一个需求一样，希望自己模拟环境

现在暂时没想到什么替代方法，比如想模拟手机端表现，还得自己调整宽高，高度太长还要拿个窗口来顶上去
![image](https://user-images.githubusercontent.com/5879146/102867360-9bc15a80-4473-11eb-9bb4-582f6144977f.png)

我现在这么做太傻了

**Comment by fyangstudio** [comment]
如果有高度定制的需求 可以使用 [Browser Preview](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) 。 

对于上述需求 我们也会讨论下

**Comment by alvinhui** [comment]
#784 和 #785 就是对预览能力的一种拓展。

调试能力下个版本我们组织评审一下。当前 Iceworks 的调试还是面向  Web 场景，未来应该也是主要服务 Web 场景。

**Comment by alvinhui** [comment]
0.18.0 已发布
