### ISSUE TITLE
RFC: 丰富的无线物料

### ISSUE THREAD

**Issue by luhc228** [ice-lab/iceworks#706]
- 通用
  - [ ] 顶部 TabBar

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606808563220-5eca8561-b4fa-402d-8bd9-8262868de0c7.png)

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607842492548-3757a4a6-0d7e-4789-b5fb-4ae463b757ad.png)

  - [ ] 数据展示

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606810550131-d56f33ee-24b1-4034-a638-2bce5afcfbb6.png)

  - [ ] 快捷入口卡片

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606810504113-37bd2944-4027-4a78-b60d-b1876588a925.png)

  - [ ] 顶部搜索组件

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607843898481-a6c0ac09-45ac-4dcc-982b-b18d65817a02.png)

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607843919641-edd945fc-7e4d-4f09-95c3-76f68692dc8d.png)

  - [ ] 弹窗确认

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606808773069-48b6012d-2fc7-4b33-9109-75fb82460da1.png)

  - [ ] 用户信息

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/195/1608694540349-02855e4f-202e-4902-a648-d44006a295ca.png)

  - [ ] 信息输入页

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607583376483-f2227291-7dbc-4b63-aff3-4730f009c3f8.png)

  - [ ] 详情页

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606809316912-79ab10ac-3165-43db-b696-bc4602e67756.png)

  - [ ] 表单页

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606811254062-b18a3830-9fcc-452f-a0a2-1e7ccf62a0a6.png)

 - [ ] 页面底部组件

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607914019886-c9c02fb1-62b8-4dba-8c2b-a774d01a9bd4.png)

  - [ ] 异常页

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607913984287-e0ad3170-4883-4f28-b6a7-7c6f071dc843.png)

  - [ ] 成功页

    ![](https://user-images.githubusercontent.com/44047106/102970754-0f766c80-4533-11eb-9035-9207487e3e54.png)

- 电商

  - [ ] 上下排布卡片

  ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607841961619-ac56bff9-88e9-401d-9fd4-55305b132f68.png)

  - [ ] 左右排布卡片

  ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607842281621-7aa4f8e4-719c-4853-9b28-b963fd2af87d.png)

  - [ ] 模块卡片

  ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607844075356-186c3a53-91e9-4f7f-be94-987dfebd84df.png)

  ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1607844122253-e959b16e-6bf5-448d-81a1-d2e1eb7970ae.png)

- 内容

  - [ ] 图表数据

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606811214673-97ae6af5-3a86-439f-858a-a5720b54ac64.png)

  - [ ] 分页搜索列表

    ![](https://intranetproxy.alipay.com/skylark/lark/0/2020/png/301926/1606814359796-79103730-faf0-4cf0-8d82-86f559a17928.png)

**Comment by luhc228** [comment]
fusion-mobile 接入 Iceworks 无线基础组件

**Comment by alvinhui** [comment]
https://github.com/raxjs/rax-materials/pull/41/files
