### ISSUE TITLE
[question]物料里如何引用非包内文件

### ISSUE THREAD

**Issue by xmsz** [ice-lab/iceworks#708]
有个文件a
```
import b from '@/c.ts'

```
但是这个c.ts并不在a的包里，而是在用户业务代码目录

举个具体一点场景
想要实现一个活动页面的物料页面，且活动页面需要进行请求数据操作
请求数据操作要用到的请求工具，这个请求工具是来自于用户最外层业务代码里的，而不是物料里封装的，因为用户可能会在请求工具中封装自己的一些需求，如果使用包内的请求的工具，那没办法使用。

问题一：要如何支持这种情况？
直接编译过不去，因为提示缺少文件（毕竟文件在用户的业务代码目录而不是当前目录）

**Comment by alvinhui** [comment]
@xmsz 就你举出的具体场景来说，为什么不将请求工具封装为一个 npm 包呢？这样业务仓库可以使用，物料仓库也可以使用。

**Comment by xmsz** [comment]
> @xmsz 就你举出的具体场景来说，为什么不将请求工具封装为一个 npm 包呢？这样业务仓库可以使用，物料仓库也可以使用。


详细就是
用户业务代码有封装好的请求工具
```
const request  = new Axios({
  baseURL: 'xxx',
  beforeRequest: (config) => {
    config.headers.token = 'xxxx'
  }
})

```
这里就配置了baseURL和每次请求都要带上token的封装。
而baseURL是和项目相关，也就是用户不同项目的baseURL是不同的
token则是当前项目环境，也就是不是固定
两个的共同点就是都是和业务环境有关，并非固定。

所以这个封装不仅仅是只是方便使用，而是和用户的业务环境有关系，只能放在用户的业务代码里

然后在物料包里没办法根据环境进行配置，除非这两个参数都是写在储存里，然后读取储存。
但只是举例子，有可能没办法从储存拿

**Comment by alvinhui** [comment]
将这个 axios 的逻辑抽一个三方包，业务仓库和物料仓库都可以使用，这样是不是可以解决问题？

就你举的这个示例来说，每次调用 axios 的方法时是可以设定 headers 的。

另外，就像你说的那样，axios 有实例的概念，可以在业务仓库里面使用 axios 时去声明一下自己的一些全局信息。这样业务库和物料库的运行时都会使用这个配置。

**Comment by xmsz** [comment]
@alvinhui 可能我的表达的不太清晰

总得说，我的需求就是

在物料包中如何引用到用户外层业务代码暴露的文件

例如，用户业务代码中有个文件request.js，暴露了request这个对象。
然后我想在物料包中使用这个对象。

要怎么处理


----- 
限制或条件：
1. 这个业务代码暴露的对象无法封装到第三方包

**Comment by alvinhui** [comment]
这个没有办法处理吧，物料库和业务库是两个独立的空间，要想相互使用公共代码，只有抽象包然后将包作为一个部分嵌入到物料库中。

也许你可以将问题再具体化一些，例如提供 codesandbox 来说明情况。

**Comment by alvinhui** [comment]
可能使用运行时方案，例如将这个 request 对象挂载到 window 中是可行的，但我不建议这样做。

**Comment by xmsz** [comment]
好吧
