### ISSUE TITLE
如何更好的解决通过物料生成业务页面/组件场景

### ISSUE THREAD

**Issue by xmsz** [ice-lab/iceworks#711]
场景一：
项目有要求新建的页面必须要引用一些组件或者做一些处理。
如果是手动创建页面，就会很浪费时间，当然也可以直接手动复制之前页面。不过还是觉得这部分时间可以省掉

尝试方案
- Dot Template
是满足了需求，但是对应的模板代码必须是在业务代码里面的，这点很不好，因为这种需求应该是属于工程化部分而不是业务代码部分，业务代码还是需要越简洁越好
所以这个方案放弃

- Iceworks
属于物料方案，创建也很方便，插件也有支持。但是并没有满足场景一。
因为在创建物料的时候，所有的文件都必须包含在物料包里，而场景一的要求可能需要引用的文件是来自类似'@\libs\xx'，这种在用户业务代码的问题，而不是包里。
所以卡在这一步

试想方案

方案一：新增物料引入方式
目前物料引入方式只有通过npm包，希望增加例如git地址这种
这样就能够解决场景一的部分问题，即上传的内容

当然新增一个功能肯定会带来更多的问题，这里先不讨论了

方案二：新增物料形式
方案一其实并没有解决问题，只是如果有肯定更好
方案二，就是想是不是有新的物料形式，可以高度和融合现有的业务代码。

就是这个物料包里可以放任何东西，但是不要求文件一定要在包里。

缺点很明显就是增加了成本，包括要求现有项目必须要包含一些文件也好，依赖也好。特别是新老项目兼容度肯定没那么高。

但是现在这种场景都是自己公司内部使用的，本身就有一些要求。所以不要考虑其他成本。

形式上和block一样，就是在某个目录下载物料，然后直接使用。

我们公司内部项目类似的就是将这些「物料」放在私有的git上，然后通过subtree来实现同步和管理。很方便解决npm包不能解决的问题

但是现在希望可以在iceworks中直接使用，不用在依赖我们自己的工具

**Comment by alvinhui** [comment]
我不能理解你需求，是否可以提供详细描述？例如你期望在 Iceworks 的什么地方添加什么洋的功能。如果可以的话，请提供产品交互图。 @xmsz
