### ISSUE TITLE
优化在 VS Code / O2 上的操作路径

### ISSUE THREAD

**Issue by luhc228** [ice-lab/iceworks#721]
### 背景

目前 Iceworks 部分功能的入口比较多，存在很大一部分用户不知道部分功能入口和操作路径。需要整理统计用户在 VS Code/O2 上的操作路径，并产出推荐的操作路径。

**Comment by alvinhui** [comment]
各个功能开发者的使用路径

**Comment by alvinhui** [comment]
## 操作入口和其路径

![image](https://user-images.githubusercontent.com/4392234/105343428-94c96b80-5c1c-11eb-8e95-6e11d4439dea.png)

## 研发链路

![image](https://user-images.githubusercontent.com/4392234/105343474-a14dc400-5c1c-11eb-96ac-0d21f50f0dc0.png)

## 功能列表及其唤起路径 

![image](https://user-images.githubusercontent.com/4392234/105343549-baef0b80-5c1c-11eb-9132-4b912b707828.png)

**Comment by alvinhui** [comment]
## 对策

明确一级入口，对根据一级入口对操作路径进行分发，形成网状的操作链路。

### 1， Explorer 侧边栏：添加 actions 和 dependencies

当且仅当是目标项目时才显示：

![image](https://user-images.githubusercontent.com/4392234/105345963-e4f5fd00-5c1f-11eb-850d-523b9be834ee.png)

**actions 结构**：

- 启动调试
- 部署发布/执行构建
- 新建页面
- ===
- 脚本列表
    - start
    - build
    - xxx

**dependencies 结构**：

- 添加依赖
- 重装依赖
- ===
- devdependences
    - xxx
    - xxx
- dependences
    - xxx
    - xxx

### 2，Iceworks 侧边栏

#### 收敛快速入口
  
![image](https://user-images.githubusercontent.com/4392234/105347437-dd375800-5c21-11eb-92b8-177851925bad.png)

更新为：

- 项目仪表盘
- 创建应用
- 欢迎页
- 设置

#### 更新 pages 和 components 视窗结构

![image](https://user-images.githubusercontent.com/4392234/105346331-664d8f80-5c20-11eb-9a22-aa57970294d4.png)

将物料的相关操作作为一级入口放到视窗下。结构如下：

**pages 结构**：

- 通过区块组装页面
- 通过模板生成页面
- ===
- 列表
    - page1
    - page2

**components 结构**：

 - 搭建组件
 - 下载区块
 - 操作2
 - ===
 - 列表
    - component1
    - component2
 
### 3，新增 Time Master 侧边栏

![image](https://user-images.githubusercontent.com/4392234/105346862-14593980-5c21-11eb-9a24-7e202c74d538.png)

### 4，更新标签栏操作入口

操作与编辑文件有关

![image](https://user-images.githubusercontent.com/4392234/105347135-6f8b2c00-5c21-11eb-99fb-8ce07ba5b7f0.png)

删除原有操作，添加以下操作：

- 添加组件
- 查找组件文档

### 5，~更新工具栏入口~

![image](https://user-images.githubusercontent.com/4392234/105684512-044a9e00-5f30-11eb-8477-b6e09cd979e6.png)

更新为：

- 启动调试
- 重装依赖
- 部署发布

### 6，保持状态栏入口

状态栏入口保持原操作，显示所有 Iceworks 可主动执行的操作列表。

![image](https://user-images.githubusercontent.com/4392234/105685778-6ce64a80-5f31-11eb-9772-f3d6cd9f9a47.png)

**Comment by alvinhui** [comment]
全部计划在 1.17.1 版本中完成发布
