### ISSUE TITLE
使用 yarn 作为包管理工具，添加组件面板点击添加后，安装业务组件出错

### ISSUE THREAD

**Issue by caiyongmin** [ice-lab/iceworks#728]
插件名/Extension: iceworks-material-helper

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: OSX EI Capitan，版本 10.11(15A284)
* Node version: v10.23.0
* npm version: 6.14.8

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them
![image](https://user-images.githubusercontent.com/11053605/104144302-ad0be000-53fd-11eb-8374-dcc50deb90bb.png)

![image](https://user-images.githubusercontent.com/11053605/104144236-674f1780-53fd-11eb-8eca-b89e30e9c3c7.png)

如标题所示的复现步骤：
1. 使用 `yarn` 作为 npm 包管理工具
2. 在快速入口，选择「打开添加组件面板」
3. 在添加组件面板点击「添加」按钮
4. 控制台开始安装，不一会儿发生报错

## 您期待的正确结果/The right result you're looking forward to

1. 不发生报错，业务组件正常安装完成

## 您有建议的解决方案，亦可进行说明/If you have a suggested solution, you can also explain it.

通过阅读代码发现，业务组件依赖安装使用的是 @iceworks//material-engine 项目下的 `addBizCode` 方法，这个方法中的安装命令没有对 packageManager 做区分，统一使用了 `install` 来安装新依赖，但 yarn 是使用 `add` 来安装新依赖，导致安装时发生报错
所以这里需要区分一下，yarn 使用 `add` 来安装新依赖，已提 PR，https://github.com/ice-lab/iceworks/pull/729

**Comment by alvinhui** [comment]
在 0.16.0 版本上已修复

**Comment by caiyongmin** [comment]
安装区块时也有相同的错误，上面的 PR 修复了这个问题
