### ISSUE TITLE
添加区块的引用名称需进行处理

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#757]
![image](https://user-images.githubusercontent.com/4392234/105951489-11d86300-60ab-11eb-98ea-8b53be48f006.png)

**Comment by luhc228** [comment]
1. 目前初始化物料的时候没有在 `package.json`加上 `blockConfig` 对象，需要修复一下 @maoxiaoke 
2. Iceworks 生成组件名到源码中，组件名需要做兼容处理。比如 `@scope/example` -> `ScopeExample` @luhc228

**Comment by luhc228** [comment]
> 1. 目前初始化物料的时候没有在 `package.json`加上 `blockConfig` 对象，需要修复一下 @maoxiaoke
> 2. Iceworks 生成组件名到源码中，组件名需要做兼容处理。比如 `@scope/example` -> `ScopeExample` @luhc228

https://github.com/ice-lab/material-templates/pull/51
https://github.com/ice-lab/iceworks/pull/761
已对应修改
