### ISSUE TITLE
tnpm 升级依赖的逻辑有误

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#759]
![image](https://user-images.githubusercontent.com/4392234/106082806-5a992600-6156-11eb-8ae5-f44beb2766ea.png)

升级依赖目前执行的脚本是：`npm update packageName`。

但是 tnpm 逻辑与 npm 不一致：`tnpm update packageName` 的行为类似于 `rm -rf node_modules && tnpm install packageName`。

解决方式有两种：

1. 反馈给 tnpm 的维护者
2. 我们的升级脚本改为：`tnpm uninstall packageName && tnpm install packageName@x.x.x`

**Comment by luhc228** [comment]
npm: `npm update packageName`
tnpm/cnpm: `tnpm uninstall packageName && tnpm i packageName`
yarn: `yarn upgrade package`
