### ISSUE TITLE
本地打包构建vscode扩展包，构建失败。有引用@ali内部包

### ISSUE THREAD

**Issue by pengxiaobao** [ice-lab/iceworks#764]
插件名/Extension:  无

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: 
* Node version: 12.18.4
* npm version: 6.14.6
* yarn version: 1.22.10

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

本地打包缺少
@ali/publis-visual
@ali/kaitian
MarketPlace API
...

```
$ git clone git@github.com:ice-lab/iceworks.git
$ cd iceworks/
$ npm install
$ npm run o2:general
```
![image](https://user-images.githubusercontent.com/13134663/106549751-982df280-654c-11eb-8947-89b826609932.png)

## 您期待的正确结果/The right result you're looking forward to
正常构建打包。

**Comment by alvinhui** [comment]
你执行的这个命令是生成内部用的 O2 包，如需打包单个插件，请进入 `extensions/xxxx `，然后执行 `vsce package`
