### ISSUE TITLE
eslint 需要升级

### ISSUE THREAD

**Issue by muzea** [ice-lab/iceworks#774]
https://github.com/ice-lab/iceworks/blob/73e6d469f5e313849d57e5c250f5c88f4a87e0cb/packages/doctor/package.json#L33

`eslint@6` 无法解析 `/* eslint-disable @iceworks/best-practices/no-js-in-ts-project */` 这类内容，需要升级到 `eslint@7`

**Comment by fyangstudio** [comment]
推荐在 .eslintrc.js 文件中配置 Custom config 关闭需要的功能

https://www.npmjs.com/package/@iceworks/spec

这里有涉及阿里 eslint 各类插件和配置，升7 影响范围较大。我们内部会再讨论和推动相关升级。

**Comment by muzea** [comment]
- 关闭只是在掩盖项目中的问题，既然有这条 rule，那它不应该被全局关闭
- eslint 作为一个被广泛应用的项目，[6 -> 7 的变化并不大](https://eslint.org/docs/user-guide/migrating-to-7.0.0#breaking-changes-for-plugin-developers)
- 我们项目同样使用 `@iceworks/spec`，使用 yarn 指定 eslint 版本到 7，eslint 是正常工作的，我不清楚 `升 7 影响范围较大`，是指什么
- 即便存在无法兼容的 break change，ice 的相关包在发版的时候 [自增主版本号](https://semver.org/) 不也是一个选择吗？

**Comment by fyangstudio** [comment]
规范基于 阿里集团前端规范
https://www.npmjs.com/package/eslint-config-ali

覆盖了很多集团项目，同时也有专门的团队在维护。
覆盖的范围和情况较多，出现问题可能会影响应用的发布和卡口，负责的同学也在回归和评估升级的影响。 
我这边知道的是云环境中有点问题，我们也在积极准备和推动升级
