### ISSUE TITLE
预览页面的插件支持手机模式

### ISSUE THREAD

**Issue by imsobear** [ice-lab/iceworks#784]
- 框架可以定义默认使用哪个模式
- 插件里可以切换其他模式/分辨率（类似 chrome devtools 那种）

![image](https://user-images.githubusercontent.com/2505411/108693849-4d930b00-7539-11eb-9e21-fb7f0508b4b4.png)

**Comment by sspku-yqLiu** [comment]
#### 框架可以定义默认使用哪个模式

添加	extension  设置。采用默认网页开发为全屏， 或指定为移动端为特定分辨率，效果如下：

![image-20210302121708951](/Users/lyq/Library/Application Support/typora-user-images/image-20210302121708951.png)



#### 插件里可以切换其他模式/分辨率（类似 chrome devtools 那种）

在点击手机按钮后可以选择分辨率。

![image-20210302122252431](/Users/lyq/Library/Application Support/typora-user-images/image-20210302122252431.png)

#### 改进想法

支持 chrome devtools 中拉伸改变分辨率的功能
