### ISSUE TITLE
iceworks 项目点击 run code 按钮不能启动。

### ISSUE THREAD

**Issue by o-x-o** [ice-lab/iceworks#798]
插件名/Extension: 
iceworks

## 您的本地环境信息/Your local environment information
苹果笔记本

* 操作系统及其版本/System and Version: macOS catalina 10.15.4
* Node version: v12.18.4
* npm version: 6.14.6

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

我的vscode装了iceworks，打开iceworks界面后，并没有npm scripts面板。
而且并不能点击右上角的启动按钮启动项目，点击之后显示 code language not supported or defined。
但是用命令行npm run start可以运行。

官方示例中有 npm scripts 面板，并且点击启动按钮可以启动，如图：
![image](https://user-images.githubusercontent.com/11014402/109506845-11335200-7ad9-11eb-9a4e-70163925fb42.png)

我的没有 npm scripts 面板，并且点击启动按钮显示 code language not supported or defined，如图：
![image](https://user-images.githubusercontent.com/11014402/109507358-9b7bb600-7ad9-11eb-8618-404fa23ddc62.png)

## 您期待的正确结果/The right result you're looking forward to

期待和官方示例一样，有 npm scripts 面板，并且点击启动按钮可以启动。

**Comment by alvinhui** [comment]
新版本的位置变了，目前启动按钮是在资源管理器面板的 Actions 视窗。

![image](https://user-images.githubusercontent.com/4392234/109636645-cbcd5e00-7b86-11eb-86b5-70b46aa631ed.png)

**Comment by o-x-o** [comment]
> 新版本的位置变了，目前启动按钮是在资源管理器面板的 Actions 视窗。
> 
> ![image](https://user-images.githubusercontent.com/4392234/109636645-cbcd5e00-7b86-11eb-86b5-70b46aa631ed.png)

thanks
