### ISSUE TITLE
did not see NPM script execution and other operations in Iceworks Side Bar.

### ISSUE THREAD

**Issue by nuptaxin** [ice-lab/iceworks#819]
插件名/Extension: Iceworks 0.18.2

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: macOS Big Sur11.1
* Node version: v15.4.0
* npm version: 7.0.14

## 您期待的正确结果/The right result you're looking forward to

After the application is created, NPM script execution/page creation/component creation and other operations are performed in Iceworks Side Bar:

i did not see NPM script execution and other operations in Iceworks Side Bar. same preform on windows10 and macOS

**Comment by alvinhui** [comment]
![image](https://user-images.githubusercontent.com/4392234/112417583-e4cec680-8d62-11eb-8138-ab7635df3059.png)

i did moved npm scripts to EXPLORER
