### ISSUE TITLE
品牌升级

### ISSUE THREAD

**Issue by alvinhui** [ice-lab/iceworks#823]
Iceworks 从 ICE 体系孵化，目前定位是面向端开发的研发套件。继续使用 [ICE]works 这个名称有些不太合适了。

打算给 Iceworks 做一次品牌升级，定位是端开发工具集：良好的开发体验和效率，打造高品质端应用。

大家出谋献策，给 Iceworks 新起一个品牌名。

名字可以来源于电影、游戏...

**Comment by alvinhui** [comment]
- webworks
- appworks

**Comment by fyangstudio** [comment]
fedworks

**Comment by sspku-yqLiu** [comment]
fedToolPack

**Comment by imsobear** [comment]
fed 是团队品牌，坚决不要用

**Comment by imsobear** [comment]
Webworker 跟 Web Worker 重复了，也不太合适

**Comment by luhc228** [comment]
1. WebDevKit

**Comment by imsobear** [comment]
ReactDevKit

**Comment by alvinhui** [comment]
表意名词:

- worker
- workman
- creator
- marker
- inventor: 发明家; 创造者; 发明者
- framer: 制定者，创作者
- deviser: 设计者，想出者; 发生器
- architect: 建筑师; 设计师; 规划者; 发起者; 创立者
- kit: 配套元件

产物名词：

- app
- web
- react

**Comment by imsobear** [comment]
我们是面向领域还是面向通用的？领域的比如 React 通用的比如 App/Web

**Comment by alvinhui** [comment]
> 我们是面向领域还是面向通用的？领域的比如 React 通用的比如 App/Web

Rax 和 React 都支持的话，是不是 App/Web 比较适合？

**Comment by alvinhui** [comment]
确定名称为 AppWorks
